project_id = "rsqfokyqntmtdejfwmjs"

[functions.delete-user-account]
verify_jwt = false

[functions.send-feedback-email]
verify_jwt = false

[functions.admin-delete-users]
verify_jwt = false

[functions.check-auth-rate-limit]
verify_jwt = false

[functions.notify-new-signup]
verify_jwt = false
