// Generated by scripts/generate-tasks-native-quick-entry-contract.mjs. Do not edit.
import Foundation

enum TasksNativeQuickEntryContract {
    static let sourceFingerprint = "5ea30f93f4269dcb3423c4a5ca3c8c9e3b505a545e2052e584d7b56cc653cfe1"
    static let schemaVersion = 1
    static let payloadSchemaVersion = 1
    static let capability = "native_quick_entry_v1"

    enum FieldID: String, CaseIterable, Codable {
        case summary = "summary"
        case start = "start"
        case reminder = "reminder"
        case deadline = "deadline"
        case area = "area"
        case actionability = "actionability"
        case notes = "notes"
        case link = "link"
        case checklist = "checklist"
    }

    enum LayoutSectionID: String, CaseIterable {
        case summary = "summary"
        case temporal = "temporal"
        case identity = "identity"
        case optional = "optional"
    }

    struct Field: Equatable {
        let id: FieldID
        let label: String
        let kind: String
        let presentation: String
        let parentFieldID: FieldID?
        let required: Bool
        let maximumCharacters: Int?
    }

    struct Option: Equatable { let value: String; let label: String }
    struct Command: Equatable { let key: String; let command: String; let fieldID: FieldID }

    struct LayoutSection: Equatable { let id: LayoutSectionID; let fieldIDs: [FieldID] }

    static let defaultDestination = "anytime"
    static let defaultTodaySection = "inbox"
    static let defaultActionability = "actionable"
    static let maximumChecklistItems = 200
    static let maximumPayloadBytes = 262144

    static let fields: [Field] = [
        .init(
            id: .summary,
            label: "Summary",
            kind: "singleLineText",
            presentation: "always",
            parentFieldID: nil,
            required: true,
            maximumCharacters: 500
        ),
        .init(
            id: .start,
            label: "Start",
            kind: "taskStart",
            presentation: "always",
            parentFieldID: nil,
            required: false,
            maximumCharacters: nil
        ),
        .init(
            id: .reminder,
            label: "Reminder",
            kind: "localTime",
            presentation: "nested",
            parentFieldID: .init(rawValue: "start"),
            required: false,
            maximumCharacters: 32
        ),
        .init(
            id: .deadline,
            label: "Deadline",
            kind: "calendarDate",
            presentation: "always",
            parentFieldID: nil,
            required: false,
            maximumCharacters: nil
        ),
        .init(
            id: .area,
            label: "Area",
            kind: "ownerReference",
            presentation: "always",
            parentFieldID: nil,
            required: false,
            maximumCharacters: nil
        ),
        .init(
            id: .actionability,
            label: "Actionability",
            kind: "singleSelect",
            presentation: "always",
            parentFieldID: nil,
            required: true,
            maximumCharacters: nil
        ),
        .init(
            id: .notes,
            label: "Notes",
            kind: "markdownText",
            presentation: "optionalDisclosure",
            parentFieldID: nil,
            required: false,
            maximumCharacters: 100000
        ),
        .init(
            id: .link,
            label: "Link",
            kind: "urlText",
            presentation: "optionalDisclosure",
            parentFieldID: nil,
            required: false,
            maximumCharacters: 8000
        ),
        .init(
            id: .checklist,
            label: "Checklist",
            kind: "orderedTextList",
            presentation: "optionalDisclosure",
            parentFieldID: nil,
            required: false,
            maximumCharacters: 500
        )
    ]

    static let layoutSections: [LayoutSection] = [
        .init(
            id: .summary,
            fieldIDs: [.summary]
        ),
        .init(
            id: .temporal,
            fieldIDs: [.start, .reminder, .deadline]
        ),
        .init(
            id: .identity,
            fieldIDs: [.area, .actionability]
        ),
        .init(
            id: .optional,
            fieldIDs: [.notes, .link, .checklist]
        )
    ]

    static let todaySections: [Option] = [
        .init(value: "inbox", label: "Inbox"),
        .init(value: "now", label: "Now"),
        .init(value: "next", label: "Next"),
        .init(value: "later", label: "Later")
    ]

    static let actionabilities: [Option] = [
        .init(value: "actionable", label: "Ready"),
        .init(value: "rechecking", label: "Rechecking"),
        .init(value: "waiting", label: "Waiting")
    ]

    static let commands: [Command] = [
        .init(
            key: "e",
            command: "open-start-date",
            fieldID: .start
        ),
        .init(
            key: "r",
            command: "clear-start",
            fieldID: .start
        ),
        .init(
            key: "t",
            command: "cycle-horizon",
            fieldID: .start
        ),
        .init(
            key: "y",
            command: "focus-reminder",
            fieldID: .reminder
        ),
        .init(
            key: "n",
            command: "focus-notes",
            fieldID: .notes
        ),
        .init(
            key: "d",
            command: "open-deadline",
            fieldID: .deadline
        ),
        .init(
            key: "f",
            command: "cycle-actionability",
            fieldID: .actionability
        ),
        .init(
            key: "g",
            command: "set-someday",
            fieldID: .start
        ),
        .init(
            key: "h",
            command: "focus-link",
            fieldID: .link
        ),
        .init(
            key: "c",
            command: "open-checklist",
            fieldID: .checklist
        ),
        .init(
            key: "v",
            command: "cycle-area",
            fieldID: .area
        )
    ]
}
