// Generated by scripts/generate-tasks-native-widget-iconography.mjs. Do not edit.
import SwiftUI

enum TaskWidgetLucideIcon: CaseIterable {
    case task
    case openTask
    case somedayTask
    case completedTask
    case deletedTask
    case today
    case upcoming
    case anytime
    case someday
    case done
    case inbox
    case now
    case next
    case later
    case recurrence
    case primaryLink
    case jiraLink
    case obsidianLink
    case mailLink
    case addTask
    case emptyState
    case complicationCheck

    var assetName: String {
        switch self {
        case .task: "TaskWidgetLucideSquareCheckBig"
        case .openTask: "TaskWidgetLucideSquare"
        case .somedayTask: "TaskWidgetLucideSquareDashed"
        case .completedTask: "TaskWidgetLucideSquareCheck"
        case .deletedTask: "TaskWidgetLucideSquareX"
        case .today: "TaskWidgetLucideStar"
        case .upcoming: "TaskWidgetLucideCalendarRange"
        case .anytime: "TaskWidgetLucideListTodo"
        case .someday: "TaskWidgetLucideSquareDashed"
        case .done: "TaskWidgetLucideListChecks"
        case .inbox: "TaskWidgetLucideInbox"
        case .now: "TaskWidgetLucideClock2"
        case .next: "TaskWidgetLucideClock5"
        case .later: "TaskWidgetLucideClock8"
        case .recurrence: "TaskWidgetLucideRepeat2"
        case .primaryLink: "TaskWidgetLucideLink2"
        case .jiraLink: "TaskWidgetLucideZap"
        case .obsidianLink: "TaskWidgetLucideFileText"
        case .mailLink: "TaskWidgetLucideMail"
        case .addTask: "TaskWidgetLucidePlus"
        case .emptyState: "TaskWidgetLucideSparkles"
        case .complicationCheck: "TaskWidgetLucideCheck"
        }
    }

    var lucideName: String {
        switch self {
        case .task: "SquareCheckBig"
        case .openTask: "Square"
        case .somedayTask: "SquareDashed"
        case .completedTask: "SquareCheck"
        case .deletedTask: "SquareX"
        case .today: "Star"
        case .upcoming: "CalendarRange"
        case .anytime: "ListTodo"
        case .someday: "SquareDashed"
        case .done: "ListChecks"
        case .inbox: "Inbox"
        case .now: "Clock2"
        case .next: "Clock5"
        case .later: "Clock8"
        case .recurrence: "Repeat2"
        case .primaryLink: "Link2"
        case .jiraLink: "Zap"
        case .obsidianLink: "FileText"
        case .mailLink: "Mail"
        case .addTask: "Plus"
        case .emptyState: "Sparkles"
        case .complicationCheck: "Check"
        }
    }
}

struct TaskWidgetLucideIconView: View {
    let icon: TaskWidgetLucideIcon

    var body: some View {
        Image(icon.assetName)
            .resizable()
            .renderingMode(.template)
            .aspectRatio(contentMode: .fit)
            .accessibilityHidden(true)
    }
}
