// Generated by scripts/generate-tasks-native-quick-entry-contract.mjs. Do not edit.
export const taskNativeQuickEntryContractFingerprint = "5ea30f93f4269dcb3423c4a5ca3c8c9e3b505a545e2052e584d7b56cc653cfe1" as const;
export const taskNativeQuickEntryContract = {
  "schemaVersion": 1,
  "payloadSchemaVersion": 1,
  "capability": "native_quick_entry_v1",
  "defaults": {
    "destination": "anytime",
    "todaySection": "inbox",
    "actionability": "actionable"
  },
  "fields": [
    {
      "id": "summary",
      "label": "Summary",
      "kind": "singleLineText",
      "presentation": "always",
      "required": true,
      "maximumCharacters": 500
    },
    {
      "id": "start",
      "label": "Start",
      "kind": "taskStart",
      "presentation": "always",
      "required": false,
      "maximumCharacters": null
    },
    {
      "id": "reminder",
      "label": "Reminder",
      "kind": "localTime",
      "presentation": "nested",
      "parentFieldId": "start",
      "required": false,
      "maximumCharacters": 32
    },
    {
      "id": "deadline",
      "label": "Deadline",
      "kind": "calendarDate",
      "presentation": "always",
      "required": false,
      "maximumCharacters": null
    },
    {
      "id": "area",
      "label": "Area",
      "kind": "ownerReference",
      "presentation": "always",
      "required": false,
      "maximumCharacters": null
    },
    {
      "id": "actionability",
      "label": "Actionability",
      "kind": "singleSelect",
      "presentation": "always",
      "required": true,
      "maximumCharacters": null
    },
    {
      "id": "notes",
      "label": "Notes",
      "kind": "markdownText",
      "presentation": "optionalDisclosure",
      "required": false,
      "maximumCharacters": 100000
    },
    {
      "id": "link",
      "label": "Link",
      "kind": "urlText",
      "presentation": "optionalDisclosure",
      "required": false,
      "maximumCharacters": 8000
    },
    {
      "id": "checklist",
      "label": "Checklist",
      "kind": "orderedTextList",
      "presentation": "optionalDisclosure",
      "required": false,
      "maximumCharacters": 500
    }
  ],
  "layoutSections": [
    {
      "id": "summary",
      "fieldIds": [
        "summary"
      ]
    },
    {
      "id": "temporal",
      "fieldIds": [
        "start",
        "reminder",
        "deadline"
      ]
    },
    {
      "id": "identity",
      "fieldIds": [
        "area",
        "actionability"
      ]
    },
    {
      "id": "optional",
      "fieldIds": [
        "notes",
        "link",
        "checklist"
      ]
    }
  ],
  "todaySections": [
    {
      "value": "inbox",
      "label": "Inbox"
    },
    {
      "value": "now",
      "label": "Now"
    },
    {
      "value": "next",
      "label": "Next"
    },
    {
      "value": "later",
      "label": "Later"
    }
  ],
  "actionabilities": [
    {
      "value": "actionable",
      "label": "Ready"
    },
    {
      "value": "rechecking",
      "label": "Rechecking"
    },
    {
      "value": "waiting",
      "label": "Waiting"
    }
  ],
  "commands": [
    {
      "key": "e",
      "command": "open-start-date",
      "fieldId": "start"
    },
    {
      "key": "r",
      "command": "clear-start",
      "fieldId": "start"
    },
    {
      "key": "t",
      "command": "cycle-horizon",
      "fieldId": "start"
    },
    {
      "key": "y",
      "command": "focus-reminder",
      "fieldId": "reminder"
    },
    {
      "key": "n",
      "command": "focus-notes",
      "fieldId": "notes"
    },
    {
      "key": "d",
      "command": "open-deadline",
      "fieldId": "deadline"
    },
    {
      "key": "f",
      "command": "cycle-actionability",
      "fieldId": "actionability"
    },
    {
      "key": "g",
      "command": "set-someday",
      "fieldId": "start"
    },
    {
      "key": "h",
      "command": "focus-link",
      "fieldId": "link"
    },
    {
      "key": "c",
      "command": "open-checklist",
      "fieldId": "checklist"
    },
    {
      "key": "v",
      "command": "cycle-area",
      "fieldId": "area"
    }
  ],
  "limits": {
    "maximumChecklistItems": 200,
    "maximumPayloadBytes": 262144
  },
  "rules": {
    "startDateMinimum": "planningDate",
    "deadlineDateMinimum": null,
    "somedayClearsPlanning": true,
    "explicitStartClearsTodaySection": true,
    "todaySectionClearsExplicitStart": true,
    "reminderRequiresStart": true,
    "emptyOptionalTextBecomesNull": true,
    "emptyChecklistItemsAreDiscarded": true
  }
} as const;
