import type {
  TaskArea,
  TaskChecklistItem,
  TaskHeading,
  TaskProject,
  TaskTodo,
} from '@/modules/tasks/types/tasks';

const timestamp = '2026-07-20T04:00:00.000Z';

export function taskTodoFixture(patch: Partial<TaskTodo> = {}): TaskTodo {
  return {
    id: 'task-a',
    owner_id: 'owner-a',
    area_id: null,
    project_id: null,
    heading_id: null,
    title: 'Task',
    notes: '',
    lifecycle: 'open',
    completed_at: null,
    canceled_at: null,
    disposition: 'present',
    deleted_at: null,
    deletion_root_id: null,
    destination: 'inbox',
    today_section: 'daytime',
    actionability: 'actionable',
    order_key: 'a0',
    hierarchy_order_key: null,
    start_date: null,
    deadline: null,
    source_kind: null,
    source_url: null,
    source_title: null,
    source_external_id: null,
    template_definition_id: null,
    template_revision: null,
    template_instantiation_id: null,
    template_node_id: null,
    recurrence_definition_id: null,
    recurrence_revision: null,
    recurrence_occurrence_id: null,
    recurrence_logical_key: null,
    undo_source_event_id: null,
    entry_channel: 'web',
    last_mutation_channel: 'web',
    last_actor_type: 'user',
    revision: 1,
    client_mutation_id: 'mutation-a',
    created_at: timestamp,
    updated_at: timestamp,
    ...patch,
  };
}

export function taskAreaFixture(patch: Partial<TaskArea> = {}): TaskArea {
  return {
    id: 'area-a',
    owner_id: 'owner-a',
    title: 'Area',
    order_key: 'a0',
    disposition: 'present',
    deleted_at: null,
    deletion_root_id: null,
    entry_channel: 'web',
    last_mutation_channel: 'web',
    last_actor_type: 'user',
    revision: 1,
    client_mutation_id: 'mutation-area-a',
    created_at: timestamp,
    updated_at: timestamp,
    ...patch,
  };
}

export function taskProjectFixture(patch: Partial<TaskProject> = {}): TaskProject {
  return {
    id: 'project-a',
    owner_id: 'owner-a',
    area_id: null,
    title: 'Project',
    notes: '',
    lifecycle: 'open',
    completed_at: null,
    canceled_at: null,
    disposition: 'present',
    deleted_at: null,
    deletion_root_id: null,
    destination: 'anytime',
    today_section: 'daytime',
    order_key: 'a0',
    planning_order_key: 'a0',
    start_date: null,
    deadline: null,
    template_definition_id: null,
    template_revision: null,
    template_instantiation_id: null,
    template_node_id: null,
    recurrence_definition_id: null,
    recurrence_revision: null,
    recurrence_occurrence_id: null,
    recurrence_logical_key: null,
    entry_channel: 'web',
    last_mutation_channel: 'web',
    last_actor_type: 'user',
    revision: 1,
    client_mutation_id: 'mutation-project-a',
    created_at: timestamp,
    updated_at: timestamp,
    ...patch,
  };
}

export function taskHeadingFixture(patch: Partial<TaskHeading> = {}): TaskHeading {
  return {
    id: 'heading-a',
    owner_id: 'owner-a',
    project_id: 'project-a',
    title: 'Heading',
    order_key: 'a0',
    disposition: 'present',
    deleted_at: null,
    deletion_root_id: null,
    template_definition_id: null,
    template_revision: null,
    template_instantiation_id: null,
    template_node_id: null,
    entry_channel: 'web',
    last_mutation_channel: 'web',
    last_actor_type: 'user',
    revision: 1,
    client_mutation_id: 'mutation-heading-a',
    created_at: timestamp,
    updated_at: timestamp,
    ...patch,
  };
}

export function taskChecklistItemFixture(
  patch: Partial<TaskChecklistItem> = {},
): TaskChecklistItem {
  return {
    id: 'checklist-a',
    owner_id: 'owner-a',
    task_id: 'task-a',
    title: 'Checklist Item',
    completed: false,
    completed_at: null,
    order_key: 'a0',
    disposition: 'present',
    deleted_at: null,
    deletion_root_id: null,
    template_definition_id: null,
    template_revision: null,
    template_instantiation_id: null,
    template_node_id: null,
    entry_channel: 'web',
    last_mutation_channel: 'web',
    last_actor_type: 'user',
    revision: 1,
    client_mutation_id: 'mutation-checklist-a',
    created_at: timestamp,
    updated_at: timestamp,
    ...patch,
  };
}
