// Generated by scripts/generate-tasks-native-quick-entry-contract.mjs. Do not edit.
export const nativeQuickEntryContractFingerprint = "5ea30f93f4269dcb3423c4a5ca3c8c9e3b505a545e2052e584d7b56cc653cfe1" as const;
export const nativeQuickEntrySchemaVersion = 1 as const;
export const nativeQuickEntryPayloadSchemaVersion = 1 as const;
export const nativeQuickEntryCapability = "native_quick_entry_v1" as const;
export const nativeQuickEntryMaximumPayloadBytes = 262144 as const;
