import {
  Archive,
  Bell,
  BellRing,
  BookOpen,
  CalendarDays,
  CalendarRange,
  CircleCheckBig,
  CircleSlash2,
  Clock2,
  Clock5,
  Clock8,
  Cloud,
  CopyCheck,
  DatabaseBackup,
  Download,
  ExternalLink,
  File,
  Filter,
  FlagTriangleRight,
  Globe2,
  HardDrive,
  Hourglass,
  Inbox,
  Layers3,
  LayoutTemplate,
  Link2,
  ListChecks,
  ListTodo,
  ListTree,
  Mail,
  Paperclip,
  Pause,
  Play,
  RefreshCw,
  Repeat2,
  RotateCcw,
  Search,
  Settings,
  SquareCheckBig,
  SquareDashed,
  SquarePlus,
  TextQuote,
  Trash2,
  Upload,
  type LucideIcon,
} from 'lucide-react';

/**
 * Canonical Lucide choices for durable Tasks concepts.
 *
 * Generic interaction chrome such as chevrons, close, confirm, ellipsis, and
 * ordering arrows stays component-local because it is not Tasks vocabulary.
 */
export const TASK_ICONS = {
  Task: SquareCheckBig,
  Project: CopyCheck,
  Area: Layers3,
  TaskChecklist: ListTree,
  Attachment: Paperclip,

  Today: CalendarDays,
  Upcoming: CalendarRange,
  Anytime: ListTodo,
  Someday: SquareDashed,
  Done: ListChecks,
  Templates: LayoutTemplate,
  Config: Settings,

  Inbox: Inbox,
  Now: Clock2,
  Next: Clock5,
  Later: Clock8,

  Reminder: Bell,
  DueReminder: BellRing,
  Deadline: FlagTriangleRight,
  PrimaryLink: ExternalLink,
  Ready: CircleCheckBig,
  Waiting: Hourglass,
  Rechecking: RotateCcw,
  Canceled: CircleSlash2,

  AddTask: SquarePlus,
  AddProject: Layers3,
  AddArea: SquarePlus,
  Search: Search,
  QuickFilters: Filter,
  Delete: Trash2,
  Reopen: RotateCcw,

  WebpageSource: Globe2,
  MailSource: Mail,
  FileSource: File,
  SelectedTextSource: TextQuote,
  ReadingItemSource: BookOpen,
  TemplateSource: LayoutTemplate,
  OtherSource: Link2,

  Recurrence: Repeat2,
  PauseRecurrence: Pause,
  ResumeRecurrence: Play,
  RegenerateRecurrence: RefreshCw,
  Archive: Archive,

  DataPortability: DatabaseBackup,
  Export: Download,
  Import: Upload,
  CloudSync: Cloud,
  LocalStorage: HardDrive,
} as const satisfies Record<string, LucideIcon>;

export type TaskIconConcept = keyof typeof TASK_ICONS;

export const TASK_ICON_NAMES = {
  Task: 'SquareCheckBig',
  Project: 'CopyCheck',
  Area: 'Layers3',
  TaskChecklist: 'ListTree',
  Attachment: 'Paperclip',

  Today: 'CalendarDays',
  Upcoming: 'CalendarRange',
  Anytime: 'ListTodo',
  Someday: 'SquareDashed',
  Done: 'ListChecks',
  Templates: 'LayoutTemplate',
  Config: 'Settings',

  Inbox: 'Inbox',
  Now: 'Clock2',
  Next: 'Clock5',
  Later: 'Clock8',

  Reminder: 'Bell',
  DueReminder: 'BellRing',
  Deadline: 'FlagTriangleRight',
  PrimaryLink: 'ExternalLink',
  Ready: 'CircleCheckBig',
  Waiting: 'Hourglass',
  Rechecking: 'RotateCcw',
  Canceled: 'CircleSlash2',

  AddTask: 'SquarePlus',
  AddProject: 'Layers3',
  AddArea: 'SquarePlus',
  Search: 'Search',
  QuickFilters: 'Filter',
  Delete: 'Trash2',
  Reopen: 'RotateCcw',

  WebpageSource: 'Globe2',
  MailSource: 'Mail',
  FileSource: 'File',
  SelectedTextSource: 'TextQuote',
  ReadingItemSource: 'BookOpen',
  TemplateSource: 'LayoutTemplate',
  OtherSource: 'Link2',

  Recurrence: 'Repeat2',
  PauseRecurrence: 'Pause',
  ResumeRecurrence: 'Play',
  RegenerateRecurrence: 'RefreshCw',
  Archive: 'Archive',

  DataPortability: 'DatabaseBackup',
  Export: 'Download',
  Import: 'Upload',
  CloudSync: 'Cloud',
  LocalStorage: 'HardDrive',
} as const satisfies Record<TaskIconConcept, string>;
