import {
  Archive,
  ArrowBigRightDash,
  Bell,
  BellRing,
  BookOpen,
  CalendarRange,
  Circle,
  CircleCheck,
  CircleSlash2,
  Clock2,
  Clock5,
  Clock8,
  Cloud,
  DatabaseBackup,
  Download,
  File,
  FileText,
  Filter,
  Flag,
  Globe2,
  HardDrive,
  Hourglass,
  Inbox,
  Layers3,
  LayoutTemplate,
  Lasso,
  Link2,
  ListChecks,
  ListTodo,
  ListTree,
  Mail,
  NotepadText,
  Paperclip,
  Pause,
  Play,
  RefreshCw,
  Repeat2,
  RotateCcw,
  Search,
  Settings,
  Square,
  SquareCheck,
  SquareCheckBig,
  SquareDashed,
  Star,
  Plus,
  TextQuote,
  Trash2,
  Upload,
  Zap,
  type LucideIcon,
} from 'lucide-react';
import type { TaskPrimaryLinkIconKind } from '@/modules/tasks/domain/taskPrimaryLink';

/**
 * Canonical Lucide choices for durable Tasks concepts.
 *
 * Generic interaction chrome such as chevrons, close, confirm, ellipsis, and
 * ordering arrows stays component-local because it is not Tasks vocabulary.
 */
export const TASK_ICONS = {
  Task: SquareCheckBig,
  OpenTask: Square,
  SomedayTask: SquareDashed,
  CompletedTask: SquareCheck,
  Selection: Circle,
  Selected: CircleCheck,
  Area: Layers3,
  Notes: NotepadText,
  TaskChecklist: ListTree,
  Attachment: Paperclip,

  Today: Star,
  Upcoming: CalendarRange,
  Anytime: ListTodo,
  Someday: SquareDashed,
  Done: ListChecks,
  Templates: LayoutTemplate,
  Config: Settings,

  Inbox: Inbox,
  Now: Clock2,
  Next: Clock5,
  Later: Clock8,

  Reminder: Bell,
  DueReminder: BellRing,
  Start: Play,
  Deadline: Flag,
  PrimaryLink: Link2,
  JiraLink: Zap,
  ObsidianLink: FileText,
  Ready: ArrowBigRightDash,
  Waiting: Hourglass,
  Rechecking: RotateCcw,
  Canceled: CircleSlash2,

  AddTask: Plus,
  AddArea: Plus,
  MultiSelect: Lasso,
  Search: Search,
  QuickFilters: Filter,
  Delete: Trash2,
  Reopen: RotateCcw,

  WebpageSource: Globe2,
  MailSource: Mail,
  FileSource: File,
  SelectedTextSource: TextQuote,
  ReadingItemSource: BookOpen,
  TemplateSource: LayoutTemplate,
  OtherSource: Link2,

  Recurrence: Repeat2,
  PauseRecurrence: Pause,
  ResumeRecurrence: Play,
  RegenerateRecurrence: RefreshCw,
  Archive: Archive,

  DataPortability: DatabaseBackup,
  Export: Download,
  Import: Upload,
  CloudSync: Cloud,
  LocalStorage: HardDrive,
} as const satisfies Record<string, LucideIcon>;

export type TaskIconConcept = keyof typeof TASK_ICONS;

export const TASK_ICON_NAMES = {
  Task: 'SquareCheckBig',
  OpenTask: 'Square',
  SomedayTask: 'SquareDashed',
  CompletedTask: 'SquareCheck',
  Selection: 'Circle',
  Selected: 'CircleCheck',
  Area: 'Layers3',
  Notes: 'NotepadText',
  TaskChecklist: 'ListTree',
  Attachment: 'Paperclip',

  Today: 'Star',
  Upcoming: 'CalendarRange',
  Anytime: 'ListTodo',
  Someday: 'SquareDashed',
  Done: 'ListChecks',
  Templates: 'LayoutTemplate',
  Config: 'Settings',

  Inbox: 'Inbox',
  Now: 'Clock2',
  Next: 'Clock5',
  Later: 'Clock8',

  Reminder: 'Bell',
  DueReminder: 'BellRing',
  Start: 'Play',
  Deadline: 'Flag',
  PrimaryLink: 'Link2',
  JiraLink: 'Zap',
  ObsidianLink: 'FileText',
  Ready: 'ArrowBigRightDash',
  Waiting: 'Hourglass',
  Rechecking: 'RotateCcw',
  Canceled: 'CircleSlash2',

  AddTask: 'Plus',
  AddArea: 'Plus',
  MultiSelect: 'Lasso',
  Search: 'Search',
  QuickFilters: 'Filter',
  Delete: 'Trash2',
  Reopen: 'RotateCcw',

  WebpageSource: 'Globe2',
  MailSource: 'Mail',
  FileSource: 'File',
  SelectedTextSource: 'TextQuote',
  ReadingItemSource: 'BookOpen',
  TemplateSource: 'LayoutTemplate',
  OtherSource: 'Link2',

  Recurrence: 'Repeat2',
  PauseRecurrence: 'Pause',
  ResumeRecurrence: 'Play',
  RegenerateRecurrence: 'RefreshCw',
  Archive: 'Archive',

  DataPortability: 'DatabaseBackup',
  Export: 'Download',
  Import: 'Upload',
  CloudSync: 'Cloud',
  LocalStorage: 'HardDrive',
} as const satisfies Record<TaskIconConcept, string>;

export const TASK_PRIMARY_LINK_ICONS = {
  mail: TASK_ICONS.MailSource,
  jira: TASK_ICONS.JiraLink,
  obsidian: TASK_ICONS.ObsidianLink,
  link: TASK_ICONS.PrimaryLink,
} as const satisfies Record<TaskPrimaryLinkIconKind, LucideIcon>;

export const TASK_PRIMARY_LINK_LABELS = {
  mail: 'Mail Link',
  jira: 'Jira Link',
  obsidian: 'Obsidian Link',
  link: 'Primary Link',
} as const satisfies Record<TaskPrimaryLinkIconKind, string>;
