// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in BathOS user's id and email.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const payload = { userId: ctx.getUserId(), email: ctx.getUserEmail() };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-garage-vehicles.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function toJson(data) {
  return {
    content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
    structuredContent: { data }
  };
}
function toError(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}

// src/lib/mcp/tools/list-garage-vehicles.ts
var list_garage_vehicles_default = defineTool2({
  name: "list_garage_vehicles",
  title: "List garage vehicles",
  description: "List the signed-in user's Garage vehicles.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return toError("Not authenticated");
    const { data, error } = await supabaseForUser(ctx).from("garage_vehicles").select("*").order("name", { ascending: true });
    if (error) return toError(error.message);
    return toJson(data);
  }
});

// src/lib/mcp/tools/list-garage-services.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var list_garage_services_default = defineTool3({
  name: "list_garage_services",
  title: "List garage services",
  description: "List Garage services, optionally filtered to one vehicle.",
  inputSchema: {
    vehicle_id: z.string().uuid().optional().describe("Optional vehicle id to filter by.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ vehicle_id }, ctx) => {
    if (!ctx.isAuthenticated()) return toError("Not authenticated");
    let query = supabaseForUser(ctx).from("garage_services").select("*");
    if (vehicle_id) query = query.eq("vehicle_id", vehicle_id);
    const { data, error } = await query;
    if (error) return toError(error.message);
    return toJson(data);
  }
});

// src/lib/mcp/tools/list-wardrobe-items.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_wardrobe_items_default = defineTool4({
  name: "list_wardrobe_items",
  title: "List wardrobe items",
  description: "List the signed-in user's Wardrobe items, optionally filtered by status.",
  inputSchema: {
    status: z2.string().optional().describe("Optional status filter (e.g. 'owned', 'wishlist')."),
    limit: z2.number().int().min(1).max(500).optional().describe("Max rows to return (default 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return toError("Not authenticated");
    let query = supabaseForUser(ctx).from("wardrobe_items").select("*").limit(limit ?? 100);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return toError(error.message);
    return toJson(data);
  }
});

// src/lib/mcp/tools/list-snake-weights.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_snake_weights_default = defineTool5({
  name: "list_snake_weights",
  title: "List snake weight records",
  description: "List Snake weight records for the signed-in user.",
  inputSchema: {
    limit: z3.number().int().min(1).max(500).optional().describe("Max rows (default 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return toError("Not authenticated");
    const { data, error } = await supabaseForUser(ctx).from("snake_weight_records").select("*").order("recorded_at", { ascending: false }).limit(limit ?? 100);
    if (error) return toError(error.message);
    return toJson(data);
  }
});

// src/lib/mcp/tools/list-budget-expenses.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_budget_expenses_default = defineTool6({
  name: "list_budget_expenses",
  title: "List budget expenses",
  description: "List Budget expenses for the signed-in user's household.",
  inputSchema: {
    limit: z4.number().int().min(1).max(500).optional().describe("Max rows (default 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return toError("Not authenticated");
    const { data, error } = await supabaseForUser(ctx).from("budget_expenses").select("*").limit(limit ?? 200);
    if (error) return toError(error.message);
    return toJson(data);
  }
});

// src/lib/mcp/index.ts
var projectRef = "rsqfokyqntmtdejfwmjs";
var mcp_default = defineMcp({
  name: "bathos-mcp",
  title: "BathOS",
  version: "0.1.0",
  instructions: "Read-only tools for the signed-in BathOS user across the Budget, Garage, Wardrobe, and Snake modules. Use `whoami` to verify connectivity.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    list_garage_vehicles_default,
    list_garage_services_default,
    list_wardrobe_items_default,
    list_snake_weights_default,
    list_budget_expenses_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
