// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/mcp-core.ts
import { auth, defineMcp, defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/tools/whoami.ts
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in BathOS user's id and email.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const payload = { userId: ctx.getUserId(), email: ctx.getUserEmail() };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function requireAuthenticated(ctx) {
  if (!ctx.isAuthenticated()) {
    throw new Error("Not authenticated");
  }
  return {
    userId: ctx.getUserId(),
    email: ctx.getUserEmail() ?? null,
    supabase: supabaseForUser(ctx)
  };
}
function nowIso() {
  return (/* @__PURE__ */ new Date()).toISOString();
}
function toJson(data) {
  return {
    content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
    structuredContent: { data }
  };
}
function toError(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function toMcpResult(promise) {
  return promise.then(toJson).catch((error) => {
    const message = error instanceof Error ? error.message : "Unexpected MCP error";
    return toError(message);
  });
}
async function resolveBudgetHousehold(auth2, requestedHouseholdId) {
  let query = auth2.supabase.from("budget_household_members").select("household_id").eq("user_id", auth2.userId).limit(1);
  if (requestedHouseholdId) {
    query = query.eq("household_id", requestedHouseholdId);
  }
  const { data, error } = await query.maybeSingle();
  if (error) throw new Error(error.message);
  if (!data?.household_id) {
    throw new Error(requestedHouseholdId ? "Budget household is not accessible." : "No Budget household found.");
  }
  return data.household_id;
}
async function resolveSnakeHousehold(auth2, requestedHouseholdId) {
  let query = auth2.supabase.from("snake_household_members").select("household_id").eq("user_id", auth2.userId).limit(1);
  if (requestedHouseholdId) {
    query = query.eq("household_id", requestedHouseholdId);
  }
  const { data, error } = await query.maybeSingle();
  if (error) throw new Error(error.message);
  if (!data?.household_id) {
    throw new Error(requestedHouseholdId ? "Snake household is not accessible." : "No Snake household found.");
  }
  return data.household_id;
}

// src/lib/mcp/resource-utils.ts
var operationSchema = z.enum(["create", "update", "delete"]);
var uuidSchema = z.string().uuid();
var jsonObjectSchema = z.record(z.unknown());
function requireId(operation, id) {
  if ((operation === "update" || operation === "delete") && !id) {
    throw new Error(`${operation} requires id.`);
  }
}
function objectData(data) {
  return data ?? {};
}
function stripOwnerFields(data) {
  const {
    id: _id,
    user_id: _userId,
    household_id: _householdId,
    created_at: _createdAt,
    updated_at: _updatedAt,
    ...rest
  } = data;
  return rest;
}
function emptyToNull(value) {
  if (typeof value !== "string") return value;
  const trimmed = value.trim();
  return trimmed ? trimmed : null;
}
function trimString(value) {
  return typeof value === "string" ? value.trim() : value;
}
function withUpdatedAt(data, now) {
  return { ...data, updated_at: now };
}

// src/lib/mcp/tools/garage-actions.ts
var garageResourceSchema = z.enum(["vehicles", "services", "servicings"]);
var serviceOutcomeSchema = z.object({
  service_id: uuidSchema,
  status: z.enum(["performed", "not_needed_yet", "declined"]).default("performed")
});
function deriveCadenceType(data) {
  const everyMiles = Number(data.every_miles ?? 0);
  const everyMonths = Number(data.every_months ?? 0);
  return everyMiles > 0 || everyMonths > 0 ? "recurring" : "no_interval";
}
async function saveServicingOutcomes(args) {
  const { error: deleteError } = await args.auth.supabase.from("garage_servicing_services").delete().eq("user_id", args.auth.userId).eq("vehicle_id", args.vehicleId).eq("servicing_id", args.servicingId);
  if (deleteError) throw new Error(deleteError.message);
  const deduped = Array.from(new Map(args.outcomes.map((outcome) => [outcome.service_id, outcome])).values());
  if (deduped.length === 0) return;
  const { error } = await args.auth.supabase.from("garage_servicing_services").insert(
    deduped.map((outcome) => ({
      user_id: args.auth.userId,
      vehicle_id: args.vehicleId,
      servicing_id: args.servicingId,
      service_id: outcome.service_id,
      status: outcome.status
    }))
  );
  if (error) throw new Error(error.message);
}
async function getGarageData(input, auth2) {
  if (input.resource === "vehicles") {
    let query2 = auth2.supabase.from("garage_vehicles").select("*").eq("user_id", auth2.userId);
    if (input.id) query2 = query2.eq("id", input.id);
    const { data: data2, error: error2 } = await query2.order("created_at", { ascending: true }).limit(input.limit ?? 500);
    if (error2) throw new Error(error2.message);
    return data2;
  }
  if (!input.vehicle_id) throw new Error(`${input.resource} requires vehicle_id.`);
  if (input.resource === "services") {
    let query2 = auth2.supabase.from("garage_services").select("*").eq("user_id", auth2.userId).eq("vehicle_id", input.vehicle_id);
    if (input.id) query2 = query2.eq("id", input.id);
    const { data: data2, error: error2 } = await query2.order("sort_order", { ascending: true }).order("name", { ascending: true }).limit(input.limit ?? 500);
    if (error2) throw new Error(error2.message);
    return data2;
  }
  let query = auth2.supabase.from("garage_servicings").select("*, outcomes:garage_servicing_services(*), receipts:garage_servicing_receipts(*)").eq("user_id", auth2.userId).eq("vehicle_id", input.vehicle_id);
  if (input.id) query = query.eq("id", input.id);
  const { data, error } = await query.order("service_date", { ascending: false }).order("created_at", { ascending: false }).limit(input.limit ?? 500);
  if (error) throw new Error(error.message);
  return data;
}
async function setGarageData(input, auth2) {
  requireId(input.operation, input.id);
  const raw = objectData(input.data);
  const clean = stripOwnerFields(raw);
  if (input.resource === "vehicles") {
    if (input.operation === "create") {
      const insert = {
        ...clean,
        user_id: auth2.userId,
        name: trimString(clean.name)
      };
      const { data, error: error3 } = await auth2.supabase.from("garage_vehicles").insert(insert).select("*").single();
      if (error3) throw new Error(error3.message);
      return data;
    }
    if (input.operation === "update") {
      const { data, error: error3 } = await auth2.supabase.from("garage_vehicles").update(withUpdatedAt({ ...clean, name: trimString(clean.name) }, nowIso())).eq("id", input.id).eq("user_id", auth2.userId).select("*").single();
      if (error3) throw new Error(error3.message);
      return data;
    }
    const { error: error2 } = await auth2.supabase.from("garage_vehicles").delete().eq("id", input.id).eq("user_id", auth2.userId);
    if (error2) throw new Error(error2.message);
    return { deleted: true, resource: input.resource, id: input.id };
  }
  const vehicleId = input.vehicle_id ?? (typeof raw.vehicle_id === "string" ? raw.vehicle_id : void 0);
  if (!vehicleId) throw new Error(`${input.resource} requires vehicle_id.`);
  if (input.resource === "services") {
    if (input.operation === "create") {
      const insert = {
        ...clean,
        user_id: auth2.userId,
        vehicle_id: vehicleId,
        name: trimString(clean.name),
        cadence_type: clean.cadence_type ?? deriveCadenceType(clean)
      };
      const { data, error: error3 } = await auth2.supabase.from("garage_services").insert(insert).select("*").single();
      if (error3) throw new Error(error3.message);
      return data;
    }
    if (input.operation === "update") {
      const update = {
        ...clean,
        name: trimString(clean.name),
        cadence_type: clean.cadence_type ?? deriveCadenceType(clean)
      };
      const { data, error: error3 } = await auth2.supabase.from("garage_services").update(withUpdatedAt(update, nowIso())).eq("id", input.id).eq("user_id", auth2.userId).eq("vehicle_id", vehicleId).select("*").single();
      if (error3) throw new Error(error3.message);
      return data;
    }
    const { error: error2 } = await auth2.supabase.from("garage_services").delete().eq("id", input.id).eq("user_id", auth2.userId).eq("vehicle_id", vehicleId);
    if (error2) throw new Error(error2.message);
    return { deleted: true, resource: input.resource, id: input.id };
  }
  if (input.operation === "create") {
    const servicingId = typeof raw.id === "string" ? raw.id : crypto.randomUUID();
    const { error: error2 } = await auth2.supabase.from("garage_servicings").insert({
      ...clean,
      id: servicingId,
      user_id: auth2.userId,
      vehicle_id: vehicleId
    });
    if (error2) throw new Error(error2.message);
    await saveServicingOutcomes({ auth: auth2, servicingId, vehicleId, outcomes: input.outcomes ?? [] });
    return (await getGarageData({ resource: "servicings", vehicle_id: vehicleId, id: servicingId }, auth2))[0] ?? { id: servicingId };
  }
  if (input.operation === "update") {
    const { error: error2 } = await auth2.supabase.from("garage_servicings").update(withUpdatedAt(clean, nowIso())).eq("id", input.id).eq("user_id", auth2.userId).eq("vehicle_id", vehicleId);
    if (error2) throw new Error(error2.message);
    if (input.outcomes) {
      await saveServicingOutcomes({ auth: auth2, servicingId: input.id, vehicleId, outcomes: input.outcomes });
    }
    return (await getGarageData({ resource: "servicings", vehicle_id: vehicleId, id: input.id }, auth2))[0] ?? { id: input.id };
  }
  const { error } = await auth2.supabase.from("garage_servicings").delete().eq("id", input.id).eq("user_id", auth2.userId).eq("vehicle_id", vehicleId);
  if (error) throw new Error(error.message);
  return { deleted: true, resource: input.resource, id: input.id };
}
var getGarage = defineTool({
  name: "get_garage",
  title: "Get Garage Data",
  description: "Read Garage vehicles, services, or servicings for the signed-in user.",
  inputSchema: {
    resource: garageResourceSchema.describe("Garage resource to read: vehicles, services, or servicings."),
    vehicle_id: uuidSchema.optional().describe("Vehicle id required for services and servicings."),
    id: uuidSchema.optional().describe("Optional record id to narrow the result."),
    limit: z.number().int().min(1).max(500).optional().describe("Max rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (input, ctx) => toMcpResult(getGarageData(input, requireAuthenticated(ctx)))
});
var setGarage = defineTool({
  name: "set_garage",
  title: "Set Garage Data",
  description: "Create, update, or delete Garage vehicles, services, or servicings for the signed-in user.",
  inputSchema: {
    resource: garageResourceSchema,
    operation: operationSchema,
    id: uuidSchema.optional().describe("Record id required for update and delete."),
    vehicle_id: uuidSchema.optional().describe("Vehicle id required for service and servicing mutations."),
    data: jsonObjectSchema.optional().describe("Record fields for create or update. Owner fields are ignored."),
    outcomes: z.array(serviceOutcomeSchema).optional().describe("Optional servicing service outcomes for servicings.")
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: false },
  handler: (input, ctx) => toMcpResult(setGarageData(input, requireAuthenticated(ctx)))
});

// src/lib/mcp/tools/snake-actions.ts
var snakeResourceSchema = z.enum(["snakes", "weight_records", "growth_expectation_ranges"]);
async function getSnakeData(input, auth2) {
  if (input.resource === "growth_expectation_ranges") {
    const { data: data2, error: error2 } = await auth2.supabase.from("snake_growth_expectation_ranges").select("*").order("profile", { ascending: true }).order("sort_order", { ascending: true });
    if (error2) throw new Error(error2.message);
    return data2;
  }
  const householdId = await resolveSnakeHousehold(auth2, input.household_id);
  if (input.resource === "snakes") {
    let query2 = auth2.supabase.from("snake_snakes").select("*").eq("household_id", householdId);
    if (input.id) query2 = query2.eq("id", input.id);
    const { data: data2, error: error2 } = await query2.order("sort_order", { ascending: true }).order("created_at", { ascending: true }).limit(input.limit ?? 500);
    if (error2) throw new Error(error2.message);
    return data2;
  }
  let query = auth2.supabase.from("snake_weight_records").select("*").eq("household_id", householdId);
  if (input.snake_id) query = query.eq("snake_id", input.snake_id);
  if (input.id) query = query.eq("id", input.id);
  const { data, error } = await query.order("recorded_on", { ascending: false }).order("created_at", { ascending: false }).limit(input.limit ?? 500);
  if (error) throw new Error(error.message);
  return data;
}
async function setSnakeData(input, auth2) {
  if (input.resource === "growth_expectation_ranges") {
    throw new Error("growth_expectation_ranges is read-only.");
  }
  requireId(input.operation, input.id);
  const householdId = await resolveSnakeHousehold(auth2, input.household_id);
  const raw = objectData(input.data);
  const clean = stripOwnerFields(raw);
  if (input.resource === "snakes") {
    const normalized = {
      ...clean,
      name: trimString(clean.name),
      species: typeof clean.species === "string" ? clean.species.trim() || "Ball Python" : clean.species,
      growth_profile: typeof clean.growth_profile === "string" ? clean.growth_profile.trim() || "ball_python" : clean.growth_profile,
      morph: emptyToNull(clean.morph),
      notes: emptyToNull(clean.notes)
    };
    if (input.operation === "create") {
      const { data, error: error3 } = await auth2.supabase.from("snake_snakes").insert({ ...normalized, household_id: householdId }).select("*").single();
      if (error3) throw new Error(error3.message);
      return data;
    }
    if (input.operation === "update") {
      const { data, error: error3 } = await auth2.supabase.from("snake_snakes").update(withUpdatedAt(normalized, nowIso())).eq("id", input.id).eq("household_id", householdId).select("*").single();
      if (error3) throw new Error(error3.message);
      return data;
    }
    const { error: error2 } = await auth2.supabase.from("snake_snakes").delete().eq("id", input.id).eq("household_id", householdId);
    if (error2) throw new Error(error2.message);
    return { deleted: true, resource: input.resource, id: input.id };
  }
  const snakeId = input.snake_id ?? (typeof raw.snake_id === "string" ? raw.snake_id : void 0);
  if (!snakeId) throw new Error("weight_records requires snake_id.");
  if (input.operation === "create") {
    const { data, error: error2 } = await auth2.supabase.from("snake_weight_records").insert({ ...clean, household_id: householdId, snake_id: snakeId }).select("*").single();
    if (error2) throw new Error(error2.message);
    return data;
  }
  if (input.operation === "update") {
    const { data, error: error2 } = await auth2.supabase.from("snake_weight_records").update(withUpdatedAt(clean, nowIso())).eq("id", input.id).eq("household_id", householdId).eq("snake_id", snakeId).select("*").single();
    if (error2) throw new Error(error2.message);
    return data;
  }
  const { error } = await auth2.supabase.from("snake_weight_records").delete().eq("id", input.id).eq("household_id", householdId).eq("snake_id", snakeId);
  if (error) throw new Error(error.message);
  return { deleted: true, resource: input.resource, id: input.id };
}
var getSnake = defineTool({
  name: "get_snake",
  title: "Get Snake Data",
  description: "Read snakes, weight records, or growth expectation ranges for an accessible Snake household.",
  inputSchema: {
    resource: snakeResourceSchema,
    household_id: uuidSchema.optional().describe("Optional accessible Snake household id."),
    snake_id: uuidSchema.optional().describe("Optional snake id for weight records."),
    id: uuidSchema.optional().describe("Optional record id to narrow the result."),
    limit: z.number().int().min(1).max(500).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (input, ctx) => toMcpResult(getSnakeData(input, requireAuthenticated(ctx)))
});
var setSnake = defineTool({
  name: "set_snake",
  title: "Set Snake Data",
  description: "Create, update, or delete snakes and weight records for an accessible Snake household.",
  inputSchema: {
    resource: z.enum(["snakes", "weight_records"]),
    operation: operationSchema,
    household_id: uuidSchema.optional(),
    snake_id: uuidSchema.optional().describe("Required for weight record mutations."),
    id: uuidSchema.optional().describe("Record id required for update and delete."),
    data: jsonObjectSchema.optional().describe("Record fields for create or update. Owner fields are ignored.")
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: false },
  handler: (input, ctx) => toMcpResult(setSnakeData(input, requireAuthenticated(ctx)))
});

// src/lib/mcp/tools/budget-actions.ts
var budgetResourceSchema = z.enum([
  "summary",
  "household_settings",
  "expenses",
  "incomes",
  "budgets",
  "categories",
  "payment_methods"
]);
function tableForResource(resource) {
  switch (resource) {
    case "expenses":
      return "budget_expenses";
    case "incomes":
      return "budget_income_streams";
    case "budgets":
      return "budget_budgets";
    case "categories":
      return "budget_categories";
    case "payment_methods":
      return "budget_linked_accounts";
    default:
      throw new Error(`${resource} is not a table-backed Budget resource.`);
  }
}
function normalizeNamed(data) {
  return {
    ...data,
    name: typeof data.name === "string" ? data.name.trim() : data.name
  };
}
function householdSettingsData(data) {
  const allowed = [
    "name",
    "partner_x_name",
    "partner_y_name",
    "wage_gap_adjustment_enabled",
    "partner_x_wage_cents_per_dollar",
    "partner_y_wage_cents_per_dollar",
    "partner_x_color",
    "partner_y_color"
  ];
  return Object.fromEntries(
    Object.entries(data).filter(([key]) => allowed.includes(key)).map(([key, value]) => [key, typeof value === "string" ? value.trim() : value])
  );
}
async function getBudgetData(input, auth2) {
  const householdId = await resolveBudgetHousehold(auth2, input.household_id);
  if (input.resource === "summary") {
    const [household, expenses, incomes, budgets, categories, paymentMethods] = await Promise.all([
      auth2.supabase.from("budget_households").select("*").eq("id", householdId).single(),
      auth2.supabase.from("budget_expenses").select("*").eq("household_id", householdId).order("created_at").limit(input.limit ?? 500),
      auth2.supabase.from("budget_income_streams").select("*").eq("household_id", householdId).order("created_at").limit(input.limit ?? 500),
      auth2.supabase.from("budget_budgets").select("*").eq("household_id", householdId).order("name").limit(input.limit ?? 500),
      auth2.supabase.from("budget_categories").select("*").eq("household_id", householdId).order("name").limit(input.limit ?? 500),
      auth2.supabase.from("budget_linked_accounts").select("*").eq("household_id", householdId).order("name").limit(input.limit ?? 500)
    ]);
    for (const result of [household, expenses, incomes, budgets, categories, paymentMethods]) {
      if (result.error) throw new Error(result.error.message);
    }
    return {
      household: household.data,
      expenses: expenses.data,
      incomes: incomes.data,
      budgets: budgets.data,
      categories: categories.data,
      payment_methods: paymentMethods.data
    };
  }
  if (input.resource === "household_settings") {
    const { data: data2, error: error2 } = await auth2.supabase.from("budget_households").select("*").eq("id", householdId).single();
    if (error2) throw new Error(error2.message);
    return data2;
  }
  const table = tableForResource(input.resource);
  let query = auth2.supabase.from(table).select("*").eq("household_id", householdId);
  if (input.id) query = query.eq("id", input.id);
  const { data, error } = await query.limit(input.limit ?? 500);
  if (error) throw new Error(error.message);
  return data;
}
async function setBudgetData(input, auth2) {
  if (input.resource === "summary") throw new Error("summary is read-only.");
  const householdId = await resolveBudgetHousehold(auth2, input.household_id);
  const clean = normalizeNamed(stripOwnerFields(objectData(input.data)));
  if (input.resource === "household_settings") {
    if (input.operation !== "update") throw new Error("household_settings only supports update.");
    const update = householdSettingsData(clean);
    if (Object.keys(update).length === 0) throw new Error("No supported household settings supplied.");
    const { data, error: error2 } = await auth2.supabase.from("budget_households").update(update).eq("id", householdId).select("*").single();
    if (error2) throw new Error(error2.message);
    return data;
  }
  requireId(input.operation, input.id);
  const table = tableForResource(input.resource);
  if (input.operation === "create") {
    const { data, error: error2 } = await auth2.supabase.from(table).insert({ ...clean, household_id: householdId }).select("*").single();
    if (error2) throw new Error(error2.message);
    return data;
  }
  if (input.operation === "update") {
    const { data, error: error2 } = await auth2.supabase.from(table).update(clean).eq("id", input.id).eq("household_id", householdId).select("*").single();
    if (error2) throw new Error(error2.message);
    return data;
  }
  const { error } = await auth2.supabase.from(table).delete().eq("id", input.id).eq("household_id", householdId);
  if (error) throw new Error(error.message);
  return { deleted: true, resource: input.resource, id: input.id };
}
var getBudget = defineTool({
  name: "get_budget",
  title: "Get Budget Data",
  description: "Read Budget household summary, settings, expenses, incomes, budgets, categories, or payment methods.",
  inputSchema: {
    resource: budgetResourceSchema,
    household_id: uuidSchema.optional().describe("Optional accessible Budget household id."),
    id: uuidSchema.optional().describe("Optional record id to narrow the result."),
    limit: z.number().int().min(1).max(500).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (input, ctx) => toMcpResult(getBudgetData(input, requireAuthenticated(ctx)))
});
var setBudget = defineTool({
  name: "set_budget",
  title: "Set Budget Data",
  description: "Create, update, or delete Budget records, or update Budget household partner settings.",
  inputSchema: {
    resource: z.enum(["household_settings", "expenses", "incomes", "budgets", "categories", "payment_methods"]),
    operation: operationSchema,
    household_id: uuidSchema.optional().describe("Optional accessible Budget household id."),
    id: uuidSchema.optional().describe("Record id required for update and delete."),
    data: jsonObjectSchema.optional().describe("Record fields for create or update. Owner fields are ignored.")
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: false },
  handler: (input, ctx) => toMcpResult(setBudgetData(input, requireAuthenticated(ctx)))
});

// src/lib/mcp/tools/wardrobe-actions.ts
var wardrobeCategorySchema = z.enum(["tops", "bottoms", "footwear", "outerwear", "underwear", "accessories"]);
var wardrobeStatusSchema = z.enum([
  "active",
  "needs_modulation",
  "endangered",
  "seeking_replacement",
  "pending_removal",
  "costume",
  "removed"
]);
function normalizeItem(data) {
  return {
    ...data,
    name: emptyToNull(data.name),
    brand: emptyToNull(data.brand),
    model: emptyToNull(data.model),
    color: emptyToNull(data.color),
    size: emptyToNull(data.size),
    link_url: emptyToNull(data.link_url),
    notes: emptyToNull(data.notes)
  };
}
async function getWardrobeData(input, auth2) {
  let query = auth2.supabase.from("wardrobe_items").select("*").eq("user_id", auth2.userId);
  if (input.id) query = query.eq("id", input.id);
  if (input.status) query = query.eq("status", input.status);
  if (input.category) query = query.eq("category", input.category);
  const { data, error } = await query.order("created_at", { ascending: true }).limit(input.limit ?? 500);
  if (error) throw new Error(error.message);
  return data;
}
async function setWardrobeData(input, auth2) {
  requireId(input.operation, input.id);
  const clean = normalizeItem(stripOwnerFields(objectData(input.data)));
  if (input.operation === "create") {
    const { data, error: error2 } = await auth2.supabase.from("wardrobe_items").insert({ ...clean, user_id: auth2.userId }).select("*").single();
    if (error2) throw new Error(error2.message);
    return data;
  }
  if (input.operation === "update") {
    const { data, error: error2 } = await auth2.supabase.from("wardrobe_items").update(withUpdatedAt(clean, nowIso())).eq("id", input.id).eq("user_id", auth2.userId).select("*").single();
    if (error2) throw new Error(error2.message);
    return data;
  }
  const { error } = await auth2.supabase.from("wardrobe_items").delete().eq("id", input.id).eq("user_id", auth2.userId);
  if (error) throw new Error(error.message);
  return { deleted: true, resource: "items", id: input.id };
}
var getWardrobe = defineTool({
  name: "get_wardrobe",
  title: "Get Wardrobe Data",
  description: "Read Wardrobe items for the signed-in user.",
  inputSchema: {
    id: uuidSchema.optional().describe("Optional item id to narrow the result."),
    status: wardrobeStatusSchema.optional(),
    category: wardrobeCategorySchema.optional(),
    limit: z.number().int().min(1).max(500).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (input, ctx) => toMcpResult(getWardrobeData(input, requireAuthenticated(ctx)))
});
var setWardrobe = defineTool({
  name: "set_wardrobe",
  title: "Set Wardrobe Data",
  description: "Create, update, or delete Wardrobe items for the signed-in user.",
  inputSchema: {
    operation: operationSchema,
    id: uuidSchema.optional().describe("Item id required for update and delete."),
    data: jsonObjectSchema.optional().describe("Item fields for create or update. Owner fields are ignored.")
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: false },
  handler: (input, ctx) => toMcpResult(setWardrobeData(input, requireAuthenticated(ctx)))
});

// src/lib/mcp/tools/tasks-read.ts
var taskRecordTypeSchema = z.enum([
  "area",
  "project",
  "heading",
  "todo",
  "checklist_item"
]);
var taskHierarchyRootTypeSchema = z.enum([
  "all",
  "area",
  "project",
  "heading",
  "todo"
]);
var taskViewSchema = z.enum([
  "inbox",
  "today",
  "upcoming",
  "anytime",
  "someday",
  "logbook",
  "trash"
]);
var planningDateSchema = z.string().regex(/^\d{4}-\d{2}-\d{2}$/);
var defaultLimit = 250;
function emptyHierarchyRows() {
  return { areas: [], projects: [], headings: [], todos: [], checklist_items: [] };
}
async function readMany(query, limit) {
  const { data, error } = await query;
  if (error) throw new Error(error.message);
  const rows = data ?? [];
  return { rows: rows.slice(0, limit), truncated: rows.length > limit };
}
async function readOne(query) {
  const { data, error } = await query;
  if (error) throw new Error(error.message);
  return data;
}
function stripOwner(row) {
  const { owner_id: _ownerId, ...record } = row;
  return record;
}
async function getOwnedTaskRecord(auth2, recordType, id) {
  if (recordType === "area") {
    return readOne(auth2.supabase.from("tasks_areas").select("*").eq("owner_id", auth2.userId).eq("id", id).maybeSingle());
  }
  if (recordType === "project") {
    return readOne(auth2.supabase.from("tasks_projects").select("*").eq("owner_id", auth2.userId).eq("id", id).maybeSingle());
  }
  if (recordType === "heading") {
    return readOne(auth2.supabase.from("tasks_headings").select("*").eq("owner_id", auth2.userId).eq("id", id).maybeSingle());
  }
  if (recordType === "todo") {
    return readOne(auth2.supabase.from("tasks_todos").select("*").eq("owner_id", auth2.userId).eq("id", id).maybeSingle());
  }
  return readOne(auth2.supabase.from("tasks_checklist_items").select("*").eq("owner_id", auth2.userId).eq("id", id).maybeSingle());
}
async function getTaskRecordData(input, auth2) {
  const record = await getOwnedTaskRecord(auth2, input.record_type, input.id);
  if (record === null) throw new Error(`Task ${input.record_type.replace("_", " ")} not found.`);
  return { record_type: input.record_type, record: stripOwner(record) };
}
async function loadAllHierarchy(auth2, includeTerminal, limit) {
  let projectsQuery = auth2.supabase.from("tasks_projects").select("*").eq("owner_id", auth2.userId).eq("disposition", "present");
  let todosQuery = auth2.supabase.from("tasks_todos").select("*").eq("owner_id", auth2.userId).eq("disposition", "present");
  if (!includeTerminal) {
    projectsQuery = projectsQuery.eq("lifecycle", "open");
    todosQuery = todosQuery.eq("lifecycle", "open");
  }
  const [areas, projects, headings, todos, checklistItems] = await Promise.all([
    readMany(auth2.supabase.from("tasks_areas").select("*").eq("owner_id", auth2.userId).eq("disposition", "present").order("order_key").order("id").limit(limit + 1), limit),
    readMany(projectsQuery.order("area_id").order("order_key").order("id").limit(limit + 1), limit),
    readMany(auth2.supabase.from("tasks_headings").select("*").eq("owner_id", auth2.userId).eq("disposition", "present").order("project_id").order("order_key").order("id").limit(limit + 1), limit),
    readMany(todosQuery.order("project_id").order("heading_id").order("hierarchy_order_key").order("id").limit(limit + 1), limit),
    readMany(auth2.supabase.from("tasks_checklist_items").select("*").eq("owner_id", auth2.userId).eq("disposition", "present").order("task_id").order("order_key").order("id").limit(limit + 1), limit)
  ]);
  const visibleProjectIds = new Set(projects.rows.map(({ id }) => id));
  const visibleTodos = todos.rows.filter(({ project_id }) => project_id === null || visibleProjectIds.has(project_id));
  const visibleTodoIds = new Set(visibleTodos.map(({ id }) => id));
  return {
    rows: {
      areas: areas.rows,
      projects: projects.rows,
      headings: headings.rows.filter(({ project_id }) => visibleProjectIds.has(project_id)),
      todos: visibleTodos,
      checklist_items: checklistItems.rows.filter(({ task_id }) => visibleTodoIds.has(task_id))
    },
    truncatedCollections: [
      areas.truncated && "areas",
      projects.truncated && "projects",
      headings.truncated && "headings",
      todos.truncated && "todos",
      checklistItems.truncated && "checklist_items"
    ].filter((name) => Boolean(name))
  };
}
function scopeHierarchyRows(rows, rootType, rootId) {
  if (rootType === "all") return rows;
  if (!rootId) throw new Error(`${rootType} hierarchy requires root_id.`);
  const result = emptyHierarchyRows();
  if (rootType === "area") {
    const area = rows.areas.find(({ id }) => id === rootId);
    if (!area) throw new Error("Task area not found within the bounded hierarchy result.");
    result.areas = [area];
    result.projects = rows.projects.filter(({ area_id }) => area_id === rootId);
    const projectIds = new Set(result.projects.map(({ id }) => id));
    result.headings = rows.headings.filter(({ project_id }) => projectIds.has(project_id));
    result.todos = rows.todos.filter(({ area_id, project_id }) => area_id === rootId || project_id !== null && projectIds.has(project_id));
  } else if (rootType === "project") {
    const project = rows.projects.find(({ id }) => id === rootId);
    if (!project) throw new Error("Task project not found within the bounded hierarchy result.");
    result.projects = [project];
    result.areas = rows.areas.filter(({ id }) => id === project.area_id);
    result.headings = rows.headings.filter(({ project_id }) => project_id === rootId);
    result.todos = rows.todos.filter(({ project_id }) => project_id === rootId);
  } else if (rootType === "heading") {
    const heading = rows.headings.find(({ id }) => id === rootId);
    if (!heading) throw new Error("Task heading not found within the bounded hierarchy result.");
    const project = rows.projects.find(({ id }) => id === heading.project_id);
    result.headings = [heading];
    result.projects = project ? [project] : [];
    result.areas = project ? rows.areas.filter(({ id }) => id === project.area_id) : [];
    result.todos = rows.todos.filter(({ heading_id }) => heading_id === rootId);
  } else {
    const todo = rows.todos.find(({ id }) => id === rootId);
    if (!todo) throw new Error("Task to-do not found within the bounded hierarchy result.");
    const project = rows.projects.find(({ id }) => id === todo.project_id);
    result.todos = [todo];
    result.projects = project ? [project] : [];
    result.headings = rows.headings.filter(({ id }) => id === todo.heading_id);
    result.areas = rows.areas.filter(({ id }) => id === (todo.area_id ?? project?.area_id));
  }
  const todoIds = new Set(result.todos.map(({ id }) => id));
  result.checklist_items = rows.checklist_items.filter(({ task_id }) => todoIds.has(task_id));
  return result;
}
async function getTaskHierarchyData(input, auth2) {
  if (input.root_type !== "all" && !input.root_id) {
    throw new Error(`${input.root_type} hierarchy requires root_id.`);
  }
  const loaded = await loadAllHierarchy(auth2, input.include_terminal, input.limit);
  const scoped = scopeHierarchyRows(loaded.rows, input.root_type, input.root_id);
  return {
    scope: { root_type: input.root_type, root_id: input.root_id ?? null },
    include_terminal: input.include_terminal,
    limit_per_collection: input.limit,
    truncated_collections: loaded.truncatedCollections,
    collections: {
      areas: scoped.areas.map(stripOwner),
      projects: scoped.projects.map(stripOwner),
      headings: scoped.headings.map(stripOwner),
      todos: scoped.todos.map(stripOwner),
      checklist_items: scoped.checklist_items.map(stripOwner)
    }
  };
}
async function getPlanningContext(auth2, requestedDate) {
  const settings = await readOne(auth2.supabase.from("tasks_user_settings").select("*").eq("owner_id", auth2.userId).maybeSingle());
  if (requestedDate) {
    return {
      planning_date: requestedDate,
      planning_timezone: settings?.planning_timezone ?? null,
      date_source: "requested"
    };
  }
  if (!settings) {
    throw new Error("Task planning settings are not initialized. Open the Tasks module once or provide planning_date.");
  }
  return {
    planning_date: planningDateInTimeZone(settings.planning_timezone),
    planning_timezone: settings.planning_timezone,
    date_source: "owner_timezone"
  };
}
function planningDateInTimeZone(timeZone, instant = /* @__PURE__ */ new Date()) {
  const parts = new Intl.DateTimeFormat("en-US", {
    timeZone,
    year: "numeric",
    month: "2-digit",
    day: "2-digit"
  }).formatToParts(instant);
  const values = Object.fromEntries(parts.map(({ type, value }) => [type, value]));
  return `${values.year}-${values.month}-${values.day}`;
}
function visibleInTaskView(row, view, planningDate) {
  if (view === "logbook") return row.disposition === "present" && row.lifecycle !== "open";
  if (row.disposition !== "present" || row.lifecycle !== "open") return false;
  if (view === "upcoming") {
    return (row.destination === "today" || row.destination === "anytime") && row.start_date !== null && row.start_date > planningDate;
  }
  return row.destination === view && (view !== "today" && view !== "anytime" || row.start_date === null || row.start_date <= planningDate);
}
function todaySection(row, planningDate) {
  return row.start_date !== null && row.start_date < planningDate ? "unfinished" : row.today_section;
}
function comparePlanningRows(left, right, view, planningDate) {
  if (view === "logbook") {
    return (right.completed_at ?? right.canceled_at ?? "").localeCompare(
      left.completed_at ?? left.canceled_at ?? ""
    ) || left.id.localeCompare(right.id);
  }
  if (view === "upcoming") {
    return (left.start_date ?? "").localeCompare(right.start_date ?? "") || planningOrder(left).localeCompare(planningOrder(right)) || left.id.localeCompare(right.id);
  }
  if (view === "today") {
    const ranks = { unfinished: 0, daytime: 1, evening: 2 };
    return ranks[todaySection(left, planningDate)] - ranks[todaySection(right, planningDate)] || planningOrder(left).localeCompare(planningOrder(right)) || left.id.localeCompare(right.id);
  }
  return planningOrder(left).localeCompare(planningOrder(right)) || left.id.localeCompare(right.id);
}
function planningOrder(row) {
  return "planning_order_key" in row ? row.planning_order_key : row.order_key;
}
async function loadPlanningRows(auth2, view, planningDate, limit) {
  const [todos, projects] = await Promise.all([
    loadTodoPlanningRows(auth2, view, planningDate, limit),
    loadProjectPlanningRows(auth2, view, planningDate, limit)
  ]);
  return {
    todos: todos.rows,
    projects: projects.rows,
    truncatedCollections: [
      todos.truncated && "todos",
      projects.truncated && "projects"
    ].filter((name) => Boolean(name))
  };
}
async function loadTodoPlanningRows(auth2, view, planningDate, limit) {
  const base = () => auth2.supabase.from("tasks_todos").select("*").eq("owner_id", auth2.userId);
  if (view === "today") {
    const todayBase = () => base().eq("destination", "today").eq("lifecycle", "open").eq("disposition", "present");
    const segments = await Promise.all([
      readMany(todayBase().lt("start_date", planningDate).order("start_date").order("order_key").order("id").limit(limit + 1), limit),
      readMany(todayBase().eq("today_section", "daytime").or(`start_date.is.null,start_date.eq.${planningDate}`).order("order_key").order("id").limit(limit + 1), limit),
      readMany(todayBase().eq("today_section", "evening").eq("start_date", planningDate).order("order_key").order("id").limit(limit + 1), limit)
    ]);
    return mergePlanningSegments(segments, view, planningDate, limit);
  }
  let query = base();
  if (view === "logbook") {
    query = query.eq("disposition", "present").in("lifecycle", ["completed", "canceled"]).order("updated_at", { ascending: false }).order("id");
  } else {
    query = query.eq("lifecycle", "open").eq("disposition", "present");
    if (view === "upcoming") {
      query = query.in("destination", ["today", "anytime"]).gt("start_date", planningDate).order("start_date").order("order_key").order("id");
    } else {
      query = query.eq("destination", view);
      if (view === "anytime") query = query.or(`start_date.is.null,start_date.lte.${planningDate}`);
      query = query.order("order_key").order("id");
    }
  }
  return readMany(query.limit(limit + 1), limit);
}
async function loadProjectPlanningRows(auth2, view, planningDate, limit) {
  const base = () => auth2.supabase.from("tasks_projects").select("*").eq("owner_id", auth2.userId);
  if (view === "today") {
    const todayBase = () => base().eq("destination", "today").eq("lifecycle", "open").eq("disposition", "present");
    const segments = await Promise.all([
      readMany(todayBase().lt("start_date", planningDate).order("start_date").order("planning_order_key").order("id").limit(limit + 1), limit),
      readMany(todayBase().eq("today_section", "daytime").or(`start_date.is.null,start_date.eq.${planningDate}`).order("planning_order_key").order("id").limit(limit + 1), limit),
      readMany(todayBase().eq("today_section", "evening").eq("start_date", planningDate).order("planning_order_key").order("id").limit(limit + 1), limit)
    ]);
    return mergePlanningSegments(segments, view, planningDate, limit);
  }
  let query = base();
  if (view === "logbook") {
    query = query.eq("disposition", "present").in("lifecycle", ["completed", "canceled"]).order("updated_at", { ascending: false }).order("id");
  } else {
    query = query.eq("lifecycle", "open").eq("disposition", "present");
    if (view === "upcoming") {
      query = query.in("destination", ["today", "anytime"]).gt("start_date", planningDate).order("start_date").order("planning_order_key").order("id");
    } else {
      query = query.eq("destination", view);
      if (view === "anytime") query = query.or(`start_date.is.null,start_date.lte.${planningDate}`);
      query = query.order("planning_order_key").order("id");
    }
  }
  return readMany(query.limit(limit + 1), limit);
}
function mergePlanningSegments(segments, view, planningDate, limit) {
  const unique = /* @__PURE__ */ new Map();
  for (const segment of segments) {
    for (const row of segment.rows) unique.set(row.id, row);
  }
  const rows = Array.from(unique.values()).filter((row) => visibleInTaskView(row, view, planningDate)).sort((left, right) => comparePlanningRows(left, right, view, planningDate));
  return {
    rows: rows.slice(0, limit),
    truncated: rows.length > limit || segments.some((segment) => segment.truncated)
  };
}
async function loadTrashRoots(auth2, limit) {
  const [areas, projects, headings, todos, checklistItems] = await Promise.all([
    readMany(auth2.supabase.from("tasks_areas").select("*").eq("owner_id", auth2.userId).eq("disposition", "deleted").order("deleted_at", { ascending: false }).limit(limit + 1), limit),
    readMany(auth2.supabase.from("tasks_projects").select("*").eq("owner_id", auth2.userId).eq("disposition", "deleted").order("deleted_at", { ascending: false }).limit(limit + 1), limit),
    readMany(auth2.supabase.from("tasks_headings").select("*").eq("owner_id", auth2.userId).eq("disposition", "deleted").order("deleted_at", { ascending: false }).limit(limit + 1), limit),
    readMany(auth2.supabase.from("tasks_todos").select("*").eq("owner_id", auth2.userId).eq("disposition", "deleted").order("deleted_at", { ascending: false }).limit(limit + 1), limit),
    readMany(auth2.supabase.from("tasks_checklist_items").select("*").eq("owner_id", auth2.userId).eq("disposition", "deleted").order("deleted_at", { ascending: false }).limit(limit + 1), limit)
  ]);
  const roots = [
    ...areas.rows.filter(({ id, deletion_root_id }) => deletion_root_id === id).map((record) => ({ root_type: "area", record })),
    ...projects.rows.filter(({ id, deletion_root_id }) => deletion_root_id === id).map((record) => ({ root_type: "project", record })),
    ...headings.rows.filter(({ id, deletion_root_id }) => deletion_root_id === id).map((record) => ({ root_type: "heading", record })),
    ...todos.rows.filter(({ id, deletion_root_id }) => deletion_root_id === id).map((record) => ({ root_type: "todo", record })),
    ...checklistItems.rows.filter(({ id, deletion_root_id }) => deletion_root_id === id).map((record) => ({ root_type: "checklist_item", record }))
  ].sort((left, right) => (right.record.deleted_at ?? "").localeCompare(left.record.deleted_at ?? "") || left.record.id.localeCompare(right.record.id));
  return {
    roots: roots.slice(0, limit).map(({ root_type, record }) => ({
      root_type,
      record: stripOwner(record)
    })),
    truncated: roots.length > limit || [areas, projects, headings, todos, checklistItems].some((collection) => collection.truncated)
  };
}
async function getTaskViewData(input, auth2) {
  const planning = await getPlanningContext(auth2, input.planning_date);
  if (input.view === "trash") {
    const trash = await loadTrashRoots(auth2, input.limit);
    return {
      view: input.view,
      ...planning,
      limit: input.limit,
      truncated: trash.truncated,
      roots: trash.roots
    };
  }
  const loaded = await loadPlanningRows(auth2, input.view, planning.planning_date, input.limit);
  return {
    view: input.view,
    ...planning,
    limit_per_collection: input.limit,
    truncated_collections: loaded.truncatedCollections,
    projects: loaded.projects.map((record) => ({
      ...stripOwner(record),
      ...input.view === "today" ? { derived_section: todaySection(record, planning.planning_date) } : {}
    })),
    todos: loaded.todos.map((record) => ({
      ...stripOwner(record),
      ...input.view === "today" ? { derived_section: todaySection(record, planning.planning_date) } : {}
    }))
  };
}
var getTaskHierarchy = defineTool({
  name: "get_task_hierarchy",
  title: "Get Task Hierarchy",
  description: "Read the signed-in user's normalized task areas, projects, headings, to-dos, and checklist items. Returns stable ids and relationship fields without mutating data.",
  inputSchema: {
    root_type: taskHierarchyRootTypeSchema.default("all").describe("Read the complete bounded hierarchy or scope it to one area, project, heading, or to-do."),
    root_id: uuidSchema.optional().describe("Required when root_type is not all."),
    include_terminal: z.boolean().default(false).describe("Include completed and canceled projects and to-dos."),
    limit: z.number().int().min(1).max(500).default(defaultLimit).describe("Maximum rows returned per hierarchy collection.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (input, ctx) => toMcpResult(getTaskHierarchyData(input, requireAuthenticated(ctx)))
});
var getTaskRecord = defineTool({
  name: "get_task_record",
  title: "Get Task Record",
  description: "Read one task area, project, heading, to-do, or checklist item by stable id for the signed-in user.",
  inputSchema: {
    record_type: taskRecordTypeSchema,
    id: uuidSchema.describe("Stable record id.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (input, ctx) => toMcpResult(getTaskRecordData(input, requireAuthenticated(ctx)))
});
var getTaskView = defineTool({
  name: "get_task_view",
  title: "Get Task Planning View",
  description: "Read the signed-in user's Inbox, Today, Upcoming, Anytime, Someday, Logbook, or Trash view using the Tasks domain rules.",
  inputSchema: {
    view: taskViewSchema,
    planning_date: planningDateSchema.optional().describe("Optional ISO calendar date for deterministic planning review. Defaults to today in the owner's stored planning time zone."),
    limit: z.number().int().min(1).max(500).default(defaultLimit).describe("Maximum projects, to-dos, or Trash roots returned.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (input, ctx) => toMcpResult(getTaskViewData(input, requireAuthenticated(ctx)))
});

// src/lib/mcp/tools/tasks-create.ts
import { assertTaskCalendarRange, isTaskCalendarDate } from "npm:@/modules/tasks/domain/taskDates";
import { generateTaskOrderKey } from "npm:@/modules/tasks/domain/taskOrder";
var destinationSchema = z.enum(["inbox", "today", "anytime", "someday"]);
var todaySectionSchema = z.enum(["daytime", "evening"]);
var integrationChannelSchema = z.enum([
  "mcp",
  "raycast",
  "browser_capture",
  "mail_automation",
  "native"
]);
var sourceKindSchema = z.enum([
  "webpage",
  "mail_message",
  "file",
  "selected_text",
  "reading_item",
  "other"
]);
var calendarDateSchema = z.string().refine(isTaskCalendarDate, {
  message: "Expected a valid ISO calendar date."
});
var sourceSchema = z.object({
  kind: sourceKindSchema,
  url: z.string().max(8e3).optional(),
  title: z.string().max(1e3).optional(),
  external_id: z.string().max(2e3).optional()
});
function trimRequired(value, label, maxLength) {
  const normalized = value.trim();
  if (!normalized) throw new Error(`${label} is required.`);
  if (Array.from(normalized).length > maxLength) {
    throw new Error(`${label} cannot exceed ${maxLength} characters.`);
  }
  return normalized;
}
function trimOptional(value) {
  const normalized = value?.trim() ?? "";
  return normalized || null;
}
function normalizeRequest(input) {
  const sourceKind = input.source?.kind ?? null;
  const sourceUrl = trimOptional(input.source?.url);
  const sourceTitle = trimOptional(input.source?.title);
  const sourceExternalId = trimOptional(input.source?.external_id);
  if ((sourceKind === "webpage" || sourceKind === "reading_item") && sourceUrl === null) {
    throw new Error("Webpage and reading-item sources require a URL.");
  }
  if (sourceUrl !== null && (sourceKind === "webpage" || sourceKind === "reading_item")) {
    let url;
    try {
      url = new URL(sourceUrl);
    } catch {
      throw new Error("Webpage and reading-item sources require a valid HTTP or HTTPS URL.");
    }
    if (url.protocol !== "http:" && url.protocol !== "https:") {
      throw new Error("Webpage and reading-item sources require a valid HTTP or HTTPS URL.");
    }
  }
  const areaId = input.area_id ?? null;
  const projectId = input.project_id ?? null;
  const headingId = input.heading_id ?? null;
  if (areaId !== null && projectId !== null) {
    throw new Error("A task cannot belong directly to both an area and a project.");
  }
  if (headingId !== null && projectId === null) {
    throw new Error("A task heading requires project membership.");
  }
  if (input.today_section === "evening" && input.destination !== "today") {
    throw new Error("This Evening is available only within Today.");
  }
  const requestedStartDate = input.start_date ?? null;
  if (requestedStartDate !== null && !isTaskCalendarDate(requestedStartDate)) {
    throw new Error("Start date must be a valid ISO calendar date.");
  }
  const deadline = input.deadline ?? null;
  if (deadline !== null && !isTaskCalendarDate(deadline)) {
    throw new Error("Deadline must be a valid ISO calendar date.");
  }
  if ((input.destination === "inbox" || input.destination === "someday") && requestedStartDate !== null) {
    throw new Error(`${input.destination === "inbox" ? "Inbox" : "Someday"} work cannot retain a start date.`);
  }
  if (requestedStartDate !== null) assertTaskCalendarRange(requestedStartDate, deadline);
  return {
    idempotencyKey: input.idempotency_key,
    title: trimRequired(input.title, "Task title", 500),
    notes: input.notes,
    destination: input.destination,
    todaySection: input.today_section,
    entryChannel: input.entry_channel ?? "mcp",
    requestedStartDate,
    startDateWasExplicit: input.start_date !== void 0 && input.start_date !== null,
    deadline,
    areaId,
    projectId,
    headingId,
    sourceKind,
    sourceUrl,
    sourceTitle,
    sourceExternalId
  };
}
async function readOne2(query) {
  const { data, error } = await query;
  if (error) throw new Error(error.message);
  return data;
}
async function findExistingCreation(auth2, idempotencyKey) {
  const event = await readOne2(auth2.supabase.from("tasks_history_events").select("task_id, client_mutation_id, actor_type, mutation_channel, affected_ids, base_revision, result_revision, transition, occurred_at, outcome, after_state").eq("owner_id", auth2.userId).eq("client_mutation_id", idempotencyKey).eq("transition", "create").maybeSingle());
  if (event === null) return null;
  const task = await readOne2(auth2.supabase.from("tasks_todos").select("*").eq("owner_id", auth2.userId).eq("id", event.task_id).maybeSingle());
  if (task === null) throw new Error("The idempotent task creation record is unavailable.");
  return { event, task };
}
function jsonRecord(value) {
  if (value === null || Array.isArray(value) || typeof value !== "object") {
    throw new Error("The idempotent task creation record is invalid.");
  }
  return value;
}
function assertSameCreationRequest(request, existing) {
  const state = jsonRecord(existing.event.after_state);
  const checks = [
    [state.title, request.title],
    [state.notes, request.notes],
    [state.destination, request.destination],
    [state.today_section, request.todaySection],
    [state.entry_channel, request.entryChannel],
    [state.deadline, request.deadline],
    [state.area_id, request.areaId],
    [state.project_id, request.projectId],
    [state.heading_id, request.headingId],
    [state.source_kind, request.sourceKind],
    [state.source_url, request.sourceUrl],
    [state.source_title, request.sourceTitle],
    [state.source_external_id, request.sourceExternalId]
  ];
  if (request.destination !== "today" || request.startDateWasExplicit) {
    checks.push([state.start_date, request.requestedStartDate]);
  }
  if (checks.some(([actual, expected]) => actual !== expected)) {
    throw new Error("The idempotency key was already used for a different task creation request.");
  }
}
async function planningDateForOwner(auth2) {
  const settings = await readOne2(auth2.supabase.from("tasks_user_settings").select("*").eq("owner_id", auth2.userId).maybeSingle());
  if (settings === null) {
    throw new Error("Task planning settings are not initialized. Open the Tasks module before creating Today work.");
  }
  return planningDateInTimeZone(settings.planning_timezone);
}
async function resolveStartDate(request, auth2) {
  if (request.destination !== "today") return request.requestedStartDate;
  const planningDate = await planningDateForOwner(auth2);
  if (request.startDateWasExplicit && request.requestedStartDate !== planningDate) {
    throw new Error(`Today work must use the owner's current planning date (${planningDate}).`);
  }
  return planningDate;
}
async function validateContainer(request, auth2) {
  const [area, project, heading] = await Promise.all([
    request.areaId === null ? null : readOne2(auth2.supabase.from("tasks_areas").select("id").eq("owner_id", auth2.userId).eq("id", request.areaId).eq("disposition", "present").maybeSingle()),
    request.projectId === null ? null : readOne2(auth2.supabase.from("tasks_projects").select("id").eq("owner_id", auth2.userId).eq("id", request.projectId).eq("disposition", "present").eq("lifecycle", "open").maybeSingle()),
    request.headingId === null ? null : readOne2(auth2.supabase.from("tasks_headings").select("id, project_id").eq("owner_id", auth2.userId).eq("id", request.headingId).eq("disposition", "present").maybeSingle())
  ]);
  if (request.areaId !== null && area === null) throw new Error("The task area is unavailable.");
  if (request.projectId !== null && project === null) throw new Error("The task project is unavailable.");
  if (request.headingId !== null && (heading === null || heading.project_id !== request.projectId)) {
    throw new Error("The task heading does not belong to the selected project.");
  }
}
async function nextPlanningOrderKey(request, startDate, auth2) {
  let query = auth2.supabase.from("tasks_todos").select("order_key").eq("owner_id", auth2.userId).eq("destination", request.destination).eq("today_section", request.todaySection).eq("lifecycle", "open").eq("disposition", "present");
  if (request.destination === "today") query = query.eq("start_date", startDate);
  const last = await readOne2(query.order("order_key", { ascending: false }).order("id", { ascending: false }).limit(1).maybeSingle());
  return generateTaskOrderKey(last?.order_key ?? null, null);
}
async function nextHierarchyOrderKey(request, auth2) {
  if (request.areaId === null && request.projectId === null && request.headingId === null) {
    return null;
  }
  let query = auth2.supabase.from("tasks_todos").select("hierarchy_order_key").eq("owner_id", auth2.userId).eq("lifecycle", "open").eq("disposition", "present");
  query = request.areaId === null ? query.is("area_id", null) : query.eq("area_id", request.areaId);
  query = request.projectId === null ? query.is("project_id", null) : query.eq("project_id", request.projectId);
  query = request.headingId === null ? query.is("heading_id", null) : query.eq("heading_id", request.headingId);
  const last = await readOne2(query.not("hierarchy_order_key", "is", null).order("hierarchy_order_key", { ascending: false }).order("id", { ascending: false }).limit(1).maybeSingle());
  return generateTaskOrderKey(last?.hierarchy_order_key ?? null, null);
}
function withoutOwner(row) {
  const { owner_id: _ownerId, ...task } = row;
  return task;
}
function creationResult(existing, idempotencyOutcome) {
  return {
    idempotency_outcome: idempotencyOutcome,
    receipt: {
      client_mutation_id: existing.event.client_mutation_id,
      actor_type: existing.event.actor_type,
      mutation_channel: existing.event.mutation_channel,
      affected_ids: existing.event.affected_ids,
      base_revision: existing.event.base_revision,
      result_revision: existing.event.result_revision,
      transition: existing.event.transition,
      occurred_at: existing.event.occurred_at,
      outcome: existing.event.outcome,
      code: null
    },
    task: withoutOwner(existing.task)
  };
}
async function readCreationEvent(auth2, idempotencyKey) {
  const created = await findExistingCreation(auth2, idempotencyKey);
  if (created === null) throw new Error("The accepted task creation receipt is unavailable.");
  return created;
}
async function createTaskData(input, auth2) {
  const request = normalizeRequest(input);
  const existing = await findExistingCreation(auth2, request.idempotencyKey);
  if (existing !== null) {
    assertSameCreationRequest(request, existing);
    return creationResult(existing, "already_applied");
  }
  const startDate = await resolveStartDate(request, auth2);
  assertTaskCalendarRange(startDate, request.deadline);
  await validateContainer(request, auth2);
  const [orderKey, hierarchyOrderKey] = await Promise.all([
    nextPlanningOrderKey(request, startDate, auth2),
    nextHierarchyOrderKey(request, auth2)
  ]);
  const timestamp = (/* @__PURE__ */ new Date()).toISOString();
  const row = {
    id: crypto.randomUUID(),
    owner_id: auth2.userId,
    area_id: request.areaId,
    project_id: request.projectId,
    heading_id: request.headingId,
    title: request.title,
    notes: request.notes,
    lifecycle: "open",
    completed_at: null,
    canceled_at: null,
    disposition: "present",
    deleted_at: null,
    deletion_root_id: null,
    destination: request.destination,
    today_section: request.todaySection,
    order_key: orderKey,
    hierarchy_order_key: hierarchyOrderKey,
    start_date: startDate,
    deadline: request.deadline,
    entry_channel: request.entryChannel,
    last_mutation_channel: request.entryChannel,
    last_actor_type: "automation",
    undo_source_event_id: null,
    source_kind: request.sourceKind,
    source_url: request.sourceUrl,
    source_title: request.sourceTitle,
    source_external_id: request.sourceExternalId,
    revision: 1,
    client_mutation_id: request.idempotencyKey,
    created_at: timestamp,
    updated_at: timestamp
  };
  const { error } = await auth2.supabase.from("tasks_todos").insert(row);
  if (error) {
    if (error.code === "23505") {
      const replay = await findExistingCreation(auth2, request.idempotencyKey);
      if (replay !== null) {
        assertSameCreationRequest(request, replay);
        return creationResult(replay, "already_applied");
      }
      throw new Error("The idempotency key is unavailable. Use a new key for a new task request.");
    }
    throw new Error(error.message);
  }
  return creationResult(await readCreationEvent(auth2, request.idempotencyKey), "created");
}
var createTask = defineTool({
  name: "create_task",
  title: "Create Task",
  description: "Create one owner-scoped to-do with structured planning and source fields. A required idempotency key makes exact retries safe.",
  inputSchema: {
    idempotency_key: uuidSchema.describe("Stable UUID for this logical creation request. Reuse it only to retry the exact same request."),
    title: z.string().trim().min(1).max(500),
    notes: z.string().max(1e5).default(""),
    destination: destinationSchema.default("inbox"),
    today_section: todaySectionSchema.default("daytime"),
    entry_channel: integrationChannelSchema.default("mcp").describe("Structured integration that collected the task. Ordinary MCP clients should keep the default."),
    start_date: calendarDateSchema.nullable().optional(),
    deadline: calendarDateSchema.nullable().optional(),
    area_id: uuidSchema.optional(),
    project_id: uuidSchema.optional(),
    heading_id: uuidSchema.optional(),
    source: sourceSchema.optional().describe("Optional typed source reference. Template provenance is reserved for template instantiation.")
  },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: (input, ctx) => toMcpResult(createTaskData(input, requireAuthenticated(ctx)))
});

// src/lib/mcp/tools/tasks-mutate.ts
import { assertTaskCalendarRange as assertTaskCalendarRange2, isTaskCalendarDate as isTaskCalendarDate2 } from "npm:@/modules/tasks/domain/taskDates";
import { generateTaskOrderKey as generateTaskOrderKey2 } from "npm:@/modules/tasks/domain/taskOrder";
import {
  applyTaskStateTransition
} from "npm:@/modules/tasks/domain/taskState";
var destinationSchema2 = z.enum(["inbox", "today", "anytime", "someday"]);
var todaySectionSchema2 = z.enum(["daytime", "evening"]);
var sourceKindSchema2 = z.enum([
  "webpage",
  "mail_message",
  "file",
  "selected_text",
  "reading_item",
  "other"
]);
var calendarDateSchema2 = z.string().refine(isTaskCalendarDate2, {
  message: "Expected a valid ISO calendar date."
});
var sourceSchema2 = z.object({
  kind: sourceKindSchema2,
  url: z.string().max(8e3).optional(),
  title: z.string().max(1e3).optional(),
  external_id: z.string().max(2e3).optional()
});
var snapshotKeys = [
  "title",
  "notes",
  "lifecycle",
  "completed_at",
  "canceled_at",
  "disposition",
  "deleted_at",
  "destination",
  "today_section",
  "order_key",
  "start_date",
  "deadline",
  "source_kind",
  "source_url",
  "source_title",
  "source_external_id",
  "area_id",
  "project_id",
  "heading_id",
  "hierarchy_order_key",
  "deletion_root_id"
];
function trimRequired2(value, label, maxLength) {
  const normalized = value.trim();
  if (!normalized) throw new Error(`${label} is required.`);
  if (Array.from(normalized).length > maxLength) {
    throw new Error(`${label} cannot exceed ${maxLength} characters.`);
  }
  return normalized;
}
function trimOptional2(value) {
  const normalized = value?.trim() ?? "";
  return normalized || null;
}
function withoutOwner2(row) {
  const { owner_id: _ownerId, ...task } = row;
  return task;
}
function jsonRecord2(value) {
  if (value === null || Array.isArray(value) || typeof value !== "object") {
    throw new Error("The accepted task mutation record is invalid.");
  }
  return value;
}
function rowSnapshot(row) {
  return Object.fromEntries(snapshotKeys.map((key) => [key, row[key]]));
}
function snapshotsMatch(actual, expected, ignored = /* @__PURE__ */ new Set()) {
  return snapshotKeys.every((key) => ignored.has(key) || actual[key] === expected[key]);
}
async function readOne3(query) {
  const { data, error } = await query;
  if (error) throw new Error(error.message);
  return data;
}
async function readMany2(query) {
  const { data, error } = await query;
  if (error) throw new Error(error.message);
  return data ?? [];
}
async function readTask(auth2, taskId) {
  return readOne3(auth2.supabase.from("tasks_todos").select("*").eq("owner_id", auth2.userId).eq("id", taskId).maybeSingle());
}
async function requireTask(auth2, taskId) {
  const task = await readTask(auth2, taskId);
  if (task === null) throw new Error("The task is unavailable.");
  return task;
}
async function readHistoryByMutation(auth2, mutationId) {
  return readOne3(auth2.supabase.from("tasks_history_events").select("*").eq("owner_id", auth2.userId).eq("client_mutation_id", mutationId).maybeSingle());
}
async function readHierarchyOperation(auth2, mutationId) {
  return readOne3(auth2.supabase.from("tasks_hierarchy_operations").select("*").eq("owner_id", auth2.userId).eq("id", mutationId).maybeSingle());
}
function historyReceipt(event) {
  return {
    client_mutation_id: event.client_mutation_id,
    actor_type: "automation",
    mutation_channel: "mcp",
    affected_ids: event.affected_ids,
    base_revision: event.base_revision,
    result_revision: event.result_revision,
    transition: event.transition,
    occurred_at: event.occurred_at,
    outcome: "accepted",
    code: event.code
  };
}
function ephemeralReceipt(input, transition, task, outcome, code) {
  return {
    client_mutation_id: input.client_mutation_id,
    actor_type: "automation",
    mutation_channel: "mcp",
    affected_ids: [task.id],
    base_revision: input.expected_revision,
    result_revision: task.revision,
    transition,
    occurred_at: (/* @__PURE__ */ new Date()).toISOString(),
    outcome,
    code
  };
}
function mutationResult(status, receipt, task) {
  return { mutation_outcome: status, receipt, task: withoutOwner2(task) };
}
function assertCurrentMutationBoundary(input, task, transition) {
  if (task.revision !== input.expected_revision) {
    return mutationResult(
      "conflict",
      ephemeralReceipt(input, transition, task, "conflict", "revision_conflict"),
      task
    );
  }
  return null;
}
function assertMutable(task) {
  if (task.disposition !== "present") {
    throw new Error("Restore the task before editing, moving, or scheduling it.");
  }
  if (task.lifecycle !== "open") {
    throw new Error("Reopen the task before editing, moving, or scheduling it.");
  }
}
function normalizeSource(source) {
  if (source === null) {
    return {
      source_kind: null,
      source_url: null,
      source_title: null,
      source_external_id: null
    };
  }
  const sourceUrl = trimOptional2(source.url);
  if ((source.kind === "webpage" || source.kind === "reading_item") && sourceUrl === null) {
    throw new Error("Webpage and reading-item sources require a URL.");
  }
  if (sourceUrl !== null && (source.kind === "webpage" || source.kind === "reading_item")) {
    let parsed;
    try {
      parsed = new URL(sourceUrl);
    } catch {
      throw new Error("Webpage and reading-item sources require a valid HTTP or HTTPS URL.");
    }
    if (parsed.protocol !== "http:" && parsed.protocol !== "https:") {
      throw new Error("Webpage and reading-item sources require a valid HTTP or HTTPS URL.");
    }
  }
  return {
    source_kind: source.kind,
    source_url: sourceUrl,
    source_title: trimOptional2(source.title),
    source_external_id: trimOptional2(source.external_id)
  };
}
function updatePatch(input) {
  if (input.title === void 0 && input.notes === void 0 && input.source === void 0) {
    throw new Error("Update at least one of title, notes, or source.");
  }
  return {
    ...input.title === void 0 ? {} : { title: trimRequired2(input.title, "Task title", 500) },
    ...input.notes === void 0 ? {} : { notes: input.notes },
    ...input.source === void 0 ? {} : normalizeSource(input.source)
  };
}
function changedPatch(current, patch) {
  return Object.fromEntries(
    Object.entries(patch).filter(([key, value]) => current[key] !== value)
  );
}
async function planningDateForOwner2(auth2, instant = /* @__PURE__ */ new Date()) {
  const settings = await readOne3(auth2.supabase.from("tasks_user_settings").select("*").eq("owner_id", auth2.userId).maybeSingle());
  if (settings === null) {
    throw new Error("Task planning settings are not initialized. Open the Tasks module first.");
  }
  return planningDateInTimeZone(settings.planning_timezone, instant);
}
function validatePlanningPlacement(destination, todaySection2, startDate, planningDate) {
  if (todaySection2 === "evening" && (destination !== "today" || startDate !== planningDate)) {
    throw new Error("This Evening requires Today and the current planning date.");
  }
  if ((destination === "inbox" || destination === "someday") && startDate !== null) {
    throw new Error(`${destination === "inbox" ? "Inbox" : "Someday"} work cannot retain a start date.`);
  }
  if (destination === "today" && startDate === null) {
    throw new Error("Today work requires a start date.");
  }
}
async function nextPlanningOrderKey2(auth2, taskId, destination, todaySection2) {
  const last = await readOne3(auth2.supabase.from("tasks_todos").select("order_key").eq("owner_id", auth2.userId).eq("destination", destination).eq("today_section", todaySection2).eq("lifecycle", "open").eq("disposition", "present").neq("id", taskId).order("order_key", { ascending: false }).order("id", { ascending: false }).limit(1).maybeSingle());
  return generateTaskOrderKey2(last?.order_key ?? null, null);
}
async function validateContainer2(auth2, areaId, projectId, headingId) {
  if (areaId !== null && projectId !== null) {
    throw new Error("A task cannot belong directly to both an area and a project.");
  }
  if (headingId !== null && projectId === null) {
    throw new Error("A task heading requires project membership.");
  }
  const [area, project, heading] = await Promise.all([
    areaId === null ? null : readOne3(auth2.supabase.from("tasks_areas").select("id").eq("owner_id", auth2.userId).eq("id", areaId).eq("disposition", "present").maybeSingle()),
    projectId === null ? null : readOne3(auth2.supabase.from("tasks_projects").select("id").eq("owner_id", auth2.userId).eq("id", projectId).eq("disposition", "present").eq("lifecycle", "open").maybeSingle()),
    headingId === null ? null : readOne3(auth2.supabase.from("tasks_headings").select("id, project_id").eq("owner_id", auth2.userId).eq("id", headingId).eq("disposition", "present").maybeSingle())
  ]);
  if (areaId !== null && area === null) throw new Error("The task area is unavailable.");
  if (projectId !== null && project === null) throw new Error("The task project is unavailable.");
  if (headingId !== null && (heading === null || heading.project_id !== projectId)) {
    throw new Error("The task heading does not belong to the selected project.");
  }
}
async function nextHierarchyOrderKey2(auth2, taskId, areaId, projectId, headingId) {
  if (areaId === null && projectId === null && headingId === null) return null;
  let query = auth2.supabase.from("tasks_todos").select("hierarchy_order_key").eq("owner_id", auth2.userId).eq("lifecycle", "open").eq("disposition", "present").neq("id", taskId);
  query = areaId === null ? query.is("area_id", null) : query.eq("area_id", areaId);
  query = projectId === null ? query.is("project_id", null) : query.eq("project_id", projectId);
  query = headingId === null ? query.is("heading_id", null) : query.eq("heading_id", headingId);
  const last = await readOne3(query.not("hierarchy_order_key", "is", null).order("hierarchy_order_key", { ascending: false }).order("id", { ascending: false }).limit(1).maybeSingle());
  return generateTaskOrderKey2(last?.hierarchy_order_key ?? null, null);
}
function hasOwn(input, key) {
  return Object.prototype.hasOwnProperty.call(input, key);
}
async function movePatch(input, current, auth2) {
  const planningRequested = input.destination !== void 0;
  if (!planningRequested && (input.today_section !== void 0 || input.start_date !== void 0)) {
    throw new Error("today_section and start_date require a destination.");
  }
  const containerKeys = ["area_id", "project_id", "heading_id"];
  const suppliedContainerKeys = containerKeys.filter((key) => hasOwn(input, key));
  if (suppliedContainerKeys.length > 0 && suppliedContainerKeys.length !== containerKeys.length) {
    throw new Error("Container moves require area_id, project_id, and heading_id together; use null to clear a value.");
  }
  if (!planningRequested && suppliedContainerKeys.length === 0) {
    throw new Error("Move either planning placement or the complete task container.");
  }
  const patch = {};
  if (planningRequested) {
    const destination = input.destination;
    const planningDate = await planningDateForOwner2(auth2);
    const todaySection2 = destination === "today" ? input.today_section ?? "daytime" : "daytime";
    let startDate = input.start_date ?? null;
    if (destination === "today") {
      if (startDate !== null && startDate !== planningDate) {
        throw new Error(`Today work must use the owner's current planning date (${planningDate}).`);
      }
      startDate = planningDate;
    }
    validatePlanningPlacement(destination, todaySection2, startDate, planningDate);
    assertTaskCalendarRange2(startDate, current.deadline);
    if (destination === current.destination && todaySection2 === current.today_section && startDate !== current.start_date) {
      throw new Error("Use schedule_task to change dates without moving planning placement.");
    }
    patch.destination = destination;
    patch.today_section = todaySection2;
    patch.start_date = startDate;
    if (destination !== current.destination || todaySection2 !== current.today_section || startDate !== current.start_date) {
      patch.order_key = await nextPlanningOrderKey2(
        auth2,
        current.id,
        destination,
        todaySection2
      );
    }
  }
  if (suppliedContainerKeys.length === containerKeys.length) {
    const areaId = input.area_id ?? null;
    const projectId = input.project_id ?? null;
    const headingId = input.heading_id ?? null;
    await validateContainer2(auth2, areaId, projectId, headingId);
    patch.area_id = areaId;
    patch.project_id = projectId;
    patch.heading_id = headingId;
    if (areaId !== current.area_id || projectId !== current.project_id || headingId !== current.heading_id) {
      patch.hierarchy_order_key = await nextHierarchyOrderKey2(
        auth2,
        current.id,
        areaId,
        projectId,
        headingId
      );
    }
  }
  return patch;
}
async function schedulePatch(input, current, auth2) {
  if (!hasOwn(input, "start_date") && !hasOwn(input, "deadline")) {
    throw new Error("Schedule at least one of start_date or deadline.");
  }
  const startDate = hasOwn(input, "start_date") ? input.start_date ?? null : current.start_date;
  const deadline = hasOwn(input, "deadline") ? input.deadline ?? null : current.deadline;
  if (startDate !== null && !isTaskCalendarDate2(startDate)) {
    throw new Error("Start date must be a valid ISO calendar date.");
  }
  if (deadline !== null && !isTaskCalendarDate2(deadline)) {
    throw new Error("Deadline must be a valid ISO calendar date.");
  }
  assertTaskCalendarRange2(startDate, deadline);
  const planningDate = await planningDateForOwner2(auth2);
  let destination = current.destination;
  let todaySection2 = current.today_section;
  if (destination === "inbox" && startDate !== null) {
    throw new Error("Move Inbox work before assigning a start date.");
  }
  if (destination === "someday" && startDate !== null) {
    destination = "anytime";
    todaySection2 = "daytime";
  }
  if (destination === "today" && startDate === null) {
    throw new Error("Today work requires a start date.");
  }
  if (todaySection2 === "evening" && startDate !== planningDate) todaySection2 = "daytime";
  validatePlanningPlacement(destination, todaySection2, startDate, planningDate);
  const patch = { start_date: startDate, deadline };
  if (destination !== current.destination) {
    patch.destination = destination;
    patch.today_section = todaySection2;
    patch.order_key = await nextPlanningOrderKey2(auth2, current.id, destination, todaySection2);
  } else if (todaySection2 !== current.today_section) {
    patch.today_section = todaySection2;
  }
  return patch;
}
function transitionPatch(input, current, occurredAt) {
  const result = applyTaskStateTransition({
    lifecycle: current.lifecycle,
    completedAt: current.completed_at,
    canceledAt: current.canceled_at,
    disposition: current.disposition,
    deletedAt: current.deleted_at
  }, input.transition, occurredAt);
  return {
    noop: result.outcome === "noop",
    patch: {
      lifecycle: result.state.lifecycle,
      completed_at: result.state.completedAt,
      canceled_at: result.state.canceledAt
    }
  };
}
function expectedAfterForRetry(request, before, after) {
  const expected = { ...before };
  const ignored = /* @__PURE__ */ new Set();
  if (request.kind === "update") {
    Object.assign(expected, updatePatch(request.input));
    return { expected, ignored, transition: "update" };
  }
  if (request.kind === "move") {
    const input = request.input;
    if (input.destination !== void 0) {
      expected.destination = input.destination;
      expected.today_section = input.destination === "today" ? input.today_section ?? "daytime" : "daytime";
      expected.start_date = input.destination === "today" ? after.start_date : input.start_date ?? null;
      ignored.add("order_key");
    }
    if (hasOwn(input, "area_id") && hasOwn(input, "project_id") && hasOwn(input, "heading_id")) {
      expected.area_id = input.area_id ?? null;
      expected.project_id = input.project_id ?? null;
      expected.heading_id = input.heading_id ?? null;
      ignored.add("hierarchy_order_key");
    }
    return { expected, ignored, transition: "move" };
  }
  if (request.kind === "schedule") {
    const input = request.input;
    if (hasOwn(input, "start_date")) expected.start_date = input.start_date ?? null;
    if (hasOwn(input, "deadline")) expected.deadline = input.deadline ?? null;
    if (before.destination === "someday" && expected.start_date !== null) {
      expected.destination = "anytime";
      expected.today_section = "daytime";
      ignored.add("order_key");
    }
    if (before.today_section === "evening" && after.today_section === "daytime") {
      expected.today_section = "daytime";
    }
    return {
      expected,
      ignored,
      transition: expected.destination === before.destination && expected.today_section === before.today_section ? "update" : "move"
    };
  }
  const transition = request.input.transition;
  if (transition === "complete") {
    expected.lifecycle = "completed";
    expected.completed_at = after.completed_at;
    expected.canceled_at = null;
  } else if (transition === "cancel") {
    expected.lifecycle = "canceled";
    expected.completed_at = null;
    expected.canceled_at = after.canceled_at;
  } else {
    expected.lifecycle = "open";
    expected.completed_at = null;
    expected.canceled_at = null;
  }
  return { expected, ignored, transition };
}
function assertExactHistoryRetry(request, event) {
  if (event.task_id !== request.input.task_id || event.base_revision !== request.input.expected_revision || event.actor_type !== "automation" || event.mutation_channel !== "mcp" || event.before_state === null) {
    throw new Error("The mutation identifier was already used for a different task request.");
  }
  const before = jsonRecord2(event.before_state);
  const after = jsonRecord2(event.after_state);
  const expected = expectedAfterForRetry(request, before, after);
  if (event.transition !== expected.transition || !snapshotsMatch(after, expected.expected, expected.ignored)) {
    throw new Error("The mutation identifier was already used for a different task request.");
  }
}
async function resolveDirectRetry(request, auth2) {
  const event = await readHistoryByMutation(auth2, request.input.client_mutation_id);
  if (event === null) return null;
  assertExactHistoryRetry(request, event);
  const task = await requireTask(auth2, event.task_id);
  return mutationResult("already_applied", historyReceipt(event), task);
}
async function writeDirectMutation(request, current, patch, transition, auth2) {
  const logicalPatch = changedPatch(rowSnapshot(current), patch);
  if (Object.keys(logicalPatch).length === 0) {
    return mutationResult(
      "noop",
      ephemeralReceipt(request.input, transition, current, "noop", "already_current"),
      current
    );
  }
  const { data, error } = await auth2.supabase.from("tasks_todos").update({
    ...logicalPatch,
    revision: current.revision + 1,
    client_mutation_id: request.input.client_mutation_id,
    last_mutation_channel: "mcp",
    last_actor_type: "automation",
    undo_source_event_id: null
  }).eq("owner_id", auth2.userId).eq("id", current.id).eq("revision", current.revision).select("*").maybeSingle();
  if (error) {
    const retry = await resolveDirectRetry(request, auth2);
    if (retry !== null) return retry;
    if (error.code === "23505") {
      throw new Error("The mutation identifier is unavailable. Use a new UUID for a new request.");
    }
    throw new Error(error.message);
  }
  if (data === null) {
    const retry = await resolveDirectRetry(request, auth2);
    if (retry !== null) return retry;
    const authoritative = await requireTask(auth2, current.id);
    return mutationResult(
      "conflict",
      ephemeralReceipt(request.input, transition, authoritative, "conflict", "revision_conflict"),
      authoritative
    );
  }
  const event = await readHistoryByMutation(auth2, request.input.client_mutation_id);
  if (event === null) throw new Error("The accepted task mutation receipt is unavailable.");
  assertExactHistoryRetry(request, event);
  return mutationResult("applied", historyReceipt(event), data);
}
async function runDirectMutation(request, auth2) {
  const retry = await resolveDirectRetry(request, auth2);
  if (retry !== null) return retry;
  if (await readHierarchyOperation(auth2, request.input.client_mutation_id) !== null) {
    throw new Error("The mutation identifier was already used for a different task request.");
  }
  const current = await requireTask(auth2, request.input.task_id);
  const transition = request.kind === "transition" ? request.input.transition : request.kind === "move" ? "move" : "update";
  const conflict = assertCurrentMutationBoundary(request.input, current, transition);
  if (conflict !== null) return conflict;
  if (request.kind === "update") {
    assertMutable(current);
    return writeDirectMutation(request, current, updatePatch(request.input), "update", auth2);
  }
  if (request.kind === "move") {
    assertMutable(current);
    return writeDirectMutation(
      request,
      current,
      await movePatch(request.input, current, auth2),
      "move",
      auth2
    );
  }
  if (request.kind === "schedule") {
    assertMutable(current);
    return writeDirectMutation(
      request,
      current,
      await schedulePatch(request.input, current, auth2),
      "update",
      auth2
    );
  }
  if (request.input.transition === "delete" || request.input.transition === "restore") {
    throw new Error("Recovery transitions require the hierarchy mutation path.");
  }
  const transitionResult = transitionPatch(request.input, current, (/* @__PURE__ */ new Date()).toISOString());
  if (transitionResult.noop) {
    return mutationResult(
      "noop",
      ephemeralReceipt(
        request.input,
        request.input.transition,
        current,
        "noop",
        "already_current"
      ),
      current
    );
  }
  return writeDirectMutation(
    request,
    current,
    transitionResult.patch,
    request.input.transition,
    auth2
  );
}
function parseRevisionMap(value) {
  const record = jsonRecord2(value);
  const parsed = {};
  for (const [id, revision] of Object.entries(record)) {
    if (typeof revision !== "number" || !Number.isSafeInteger(revision) || revision < 1) {
      throw new Error("The hierarchy mutation receipt is invalid.");
    }
    parsed[id] = revision;
  }
  return parsed;
}
function hierarchyReceipt(operation) {
  const base = parseRevisionMap(operation.expected_revisions);
  const result = parseRevisionMap(operation.result_revisions);
  const affectedIds = operation.affected_ids.length > 0 ? operation.affected_ids : Object.keys(base);
  return {
    client_mutation_id: operation.id,
    actor_type: "automation",
    mutation_channel: "mcp",
    affected_ids: affectedIds,
    base_revision: base[operation.root_id] ?? 0,
    result_revision: result[operation.root_id] ?? base[operation.root_id] ?? 0,
    affected_revisions: Object.fromEntries(affectedIds.map((id) => [id, {
      base_revision: base[id] ?? 0,
      result_revision: result[id] ?? base[id] ?? 0
    }])),
    transition: operation.operation,
    occurred_at: operation.completed_at ?? operation.requested_at,
    outcome: operation.outcome === "pending" ? "rejected" : operation.outcome,
    code: operation.outcome === "pending" ? "operation_pending" : operation.code
  };
}
function assertExactHierarchyRetry(input, operation) {
  const base = parseRevisionMap(operation.expected_revisions);
  if (operation.root_type !== "todo" || operation.root_id !== input.task_id || operation.operation !== input.transition || operation.descendant_policy !== "cascade" || operation.actor_type !== "automation" || operation.mutation_channel !== "mcp" || base[input.task_id] !== input.expected_revision) {
    throw new Error("The mutation identifier was already used for a different task request.");
  }
}
async function hierarchyResult(input, operation, auth2, retry) {
  assertExactHierarchyRetry(input, operation);
  const task = await requireTask(auth2, input.task_id);
  const receipt = hierarchyReceipt(operation);
  const status = retry && (operation.outcome === "accepted" || operation.outcome === "noop") ? "already_applied" : operation.outcome === "accepted" ? "applied" : operation.outcome === "noop" ? "noop" : operation.outcome === "conflict" ? "conflict" : "rejected";
  return mutationResult(status, receipt, task);
}
async function expectedHierarchyRevisions(input, current, auth2) {
  let query = auth2.supabase.from("tasks_checklist_items").select("id, revision").eq("owner_id", auth2.userId);
  query = input.transition === "delete" ? query.eq("task_id", current.id).eq("disposition", "present") : query.eq("deletion_root_id", current.id);
  const descendants = await readMany2(query);
  return Object.fromEntries([
    [current.id, current.revision],
    ...descendants.map((row) => [row.id, row.revision])
  ]);
}
async function runRecoveryTransition(input, auth2) {
  const existing = await readHierarchyOperation(auth2, input.client_mutation_id);
  if (existing !== null) return hierarchyResult(input, existing, auth2, true);
  if (await readHistoryByMutation(auth2, input.client_mutation_id) !== null) {
    throw new Error("The mutation identifier was already used for a different task request.");
  }
  const current = await requireTask(auth2, input.task_id);
  const conflict = assertCurrentMutationBoundary(input, current, input.transition);
  if (conflict !== null) return conflict;
  const alreadyCurrent = input.transition === "delete" && current.disposition === "deleted" || input.transition === "restore" && current.disposition === "present";
  if (alreadyCurrent) {
    return mutationResult(
      "noop",
      ephemeralReceipt(input, input.transition, current, "noop", "already_current"),
      current
    );
  }
  const requestedAt = (/* @__PURE__ */ new Date()).toISOString();
  const operation = {
    id: input.client_mutation_id,
    owner_id: auth2.userId,
    root_type: "todo",
    root_id: current.id,
    operation: input.transition,
    descendant_policy: "cascade",
    expected_revisions: await expectedHierarchyRevisions(input, current, auth2),
    actor_type: "automation",
    mutation_channel: "mcp",
    requested_at: requestedAt,
    outcome: "pending",
    code: null,
    affected_ids: [],
    result_revisions: {},
    completed_at: null
  };
  const { error } = await auth2.supabase.from("tasks_hierarchy_operations").insert(operation);
  if (error) {
    const replay = await readHierarchyOperation(auth2, input.client_mutation_id);
    if (replay !== null) return hierarchyResult(input, replay, auth2, true);
    if (error.code === "23505") {
      throw new Error("The mutation identifier is unavailable. Use a new UUID for a new request.");
    }
    throw new Error(error.message);
  }
  const accepted = await readHierarchyOperation(auth2, input.client_mutation_id);
  if (accepted === null) throw new Error("The hierarchy mutation receipt is unavailable.");
  return hierarchyResult(input, accepted, auth2, false);
}
function updateTaskData(input, auth2) {
  return runDirectMutation({ kind: "update", input }, auth2);
}
function moveTaskData(input, auth2) {
  return runDirectMutation({ kind: "move", input }, auth2);
}
function scheduleTaskData(input, auth2) {
  return runDirectMutation({ kind: "schedule", input }, auth2);
}
function transitionTaskData(input, auth2) {
  return input.transition === "delete" || input.transition === "restore" ? runRecoveryTransition(input, auth2) : runDirectMutation({ kind: "transition", input }, auth2);
}
var mutationBaseSchema = {
  task_id: uuidSchema.describe("Stable to-do identifier."),
  expected_revision: z.number().int().positive().describe("Current revision returned by a task read."),
  client_mutation_id: uuidSchema.describe("Stable UUID for this logical mutation. Reuse it only to retry the exact same request.")
};
var updateTask = defineTool({
  name: "update_task",
  title: "Update Task",
  description: "Edit one current to-do title, notes, or complete typed source reference with an optimistic revision guard.",
  inputSchema: {
    ...mutationBaseSchema,
    title: z.string().max(500).optional(),
    notes: z.string().max(1e5).optional(),
    source: sourceSchema2.nullable().optional().describe("Complete replacement source, null to clear, or omit to preserve.")
  },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: (input, ctx) => toMcpResult(updateTaskData(input, requireAuthenticated(ctx)))
});
var moveTask = defineTool({
  name: "move_task",
  title: "Move Task",
  description: "Move one open to-do between planning placements, hierarchy containers, or both. Container changes require all three container IDs, using null to clear.",
  inputSchema: {
    ...mutationBaseSchema,
    destination: destinationSchema2.optional(),
    today_section: todaySectionSchema2.optional(),
    start_date: calendarDateSchema2.nullable().optional(),
    area_id: uuidSchema.nullable().optional(),
    project_id: uuidSchema.nullable().optional(),
    heading_id: uuidSchema.nullable().optional()
  },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: (input, ctx) => toMcpResult(moveTaskData(input, requireAuthenticated(ctx)))
});
var scheduleTask = defineTool({
  name: "schedule_task",
  title: "Schedule Task",
  description: "Set or clear one open to-do start date or deadline without accepting timestamps or time-zone offsets.",
  inputSchema: {
    ...mutationBaseSchema,
    start_date: calendarDateSchema2.nullable().optional(),
    deadline: calendarDateSchema2.nullable().optional()
  },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: (input, ctx) => toMcpResult(scheduleTaskData(input, requireAuthenticated(ctx)))
});
var transitionTask = defineTool({
  name: "transition_task",
  title: "Transition Task",
  description: "Complete, cancel, reopen, recoverably delete, or restore one to-do. Permanent deletion is not available.",
  inputSchema: {
    ...mutationBaseSchema,
    transition: z.enum(["complete", "cancel", "reopen", "delete", "restore"])
  },
  annotations: { readOnlyHint: false, idempotentHint: true, destructiveHint: false, openWorldHint: false },
  handler: (input, ctx) => toMcpResult(transitionTaskData(input, requireAuthenticated(ctx)))
});

// src/lib/mcp/index.ts
var projectRef = "rsqfokyqntmtdejfwmjs";
var mcp_default = defineMcp({
  name: "bathos-mcp",
  title: "BathOS",
  version: "0.1.0",
  instructions: "Authenticated tools for the signed-in BathOS user across Budget, Garage, Snake, Tasks, and Wardrobe. Use `whoami` to verify connectivity. Read with get_* tools. Tasks expose owner-scoped hierarchy, record, and planning views plus guarded create, update, move, schedule, and lifecycle or recovery mutations. Use task mutations only when the user clearly asks, read the current revision first, and never reuse a mutation UUID for a different request. Task deletion is recoverable; permanent deletion is unavailable. Mutate other modules only when the user clearly asks, using set_* tools scoped by the signed-in user or accessible household. Receipt files, household lifecycle actions, and restore execution are out of scope.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    getGarage,
    setGarage,
    getSnake,
    setSnake,
    getBudget,
    setBudget,
    getWardrobe,
    setWardrobe,
    getTaskHierarchy,
    getTaskRecord,
    getTaskView,
    createTask,
    updateTask,
    moveTask,
    scheduleTask,
    transitionTask
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
